---
title: "Analysis"
author: "April Peterson"
output:
  html_document: default
  pdf_document: default
---


```{r setup, echo=FALSE, include = FALSE}
library(knitr)
library(ggplot2)
#library(pwr)
library(plyr)
library(lattice)
library(dplyr)
library(raster)
library(lme4)
library(nlme)
library(RLRsim)
library(ggpubr)
library(reshape2)
library(writexl)
library(xlsx)
#library(patchwork)

options(digits=2)
#setwd("~.")

#just load the data_setup, since I load most everything else

load(file = "~./MeioticRecombSexualDimorphism/data/MLH1_data_setup_7.30.20.RData")#added SKIVE_f BiveData
#load(file = "~./MLH1repo/data/MLH1/MLH1_data_setup_5.21.20.RData")

#load functions
source("~./MeioticRecombSexualDimorphism/src/CommonFunc_MLH1repo.R")
```



```{r MLH1.FEMALE.TABLE, echo=FALSE, eval=TRUE}
female_mouse.avs_for.analysis <-  Mouse.Table_HQ %>% filter(sex== "female") %>% filter(species == "M.musculus")

female_mouse.avs_for.analysis$subsp <- factor(female_mouse.avs_for.analysis$subsp, ordered = FALSE)
female_mouse.avs_for.analysis$sex <- factor(female_mouse.avs_for.analysis$sex, ordered = FALSE)
female_mouse.avs_for.analysis$strain <- factor(female_mouse.avs_for.analysis$strain, ordered = FALSE)
female_mouse.avs_for.analysis$species <- factor(female_mouse.avs_for.analysis$species, ordered = FALSE)

```


```{r MLH1.MALE.TABLE, echo=FALSE, eval=TRUE}

male_mouse.avs_for.analysis <-  Mouse.Table_HQ %>% filter(sex== "male") %>% filter(species == "M.musculus") 

male_mouse.avs_for.analysis$subsp <- factor(male_mouse.avs_for.analysis$subsp, ordered = FALSE)
male_mouse.avs_for.analysis$sex <- factor(male_mouse.avs_for.analysis$sex, ordered = FALSE)
male_mouse.avs_for.analysis$strain <- factor(male_mouse.avs_for.analysis$strain, ordered = FALSE)
male_mouse.avs_for.analysis$species <- factor(male_mouse.avs_for.analysis$species, ordered = FALSE)

#how much greater are the High Rec gwRRs
male_mouse.avs_for.analysis$Rec.group <- ifelse(grepl("PWD", male_mouse.avs_for.analysis$strain), 1, 
                              ifelse(grepl("MSM", male_mouse.avs_for.analysis$strain), 1,
                                ifelse(grepl("SKIVE", male_mouse.avs_for.analysis$strain), 1, 0)))


Musc.male_mouse.av <-  male_mouse.avs_for.analysis %>% filter(sex== "male") %>% filter(subsp == "Musc")
Mol.male_mouse.av <-  male_mouse.avs_for.analysis %>% filter(sex== "male") %>% filter(subsp == "Mol")
#Dom version 
Dom.male_mouse.av <-  male_mouse.avs_for.analysis %>% filter(sex== "male") %>% filter(subsp == "Dom")

```


```{r female.diference, echo=FALSE}

#how much greater are the high strains?
G_female <-  female_mouse.avs_for.analysis %>% filter(strain == "G")
mean.G.female <- mean(G_female$mean_co, na.rm=TRUE)

LEW_female <-  female_mouse.avs_for.analysis %>% filter(strain == "LEW")
mean.LEW.female <- mean(LEW_female$mean_co, na.rm=TRUE)

#how much greater is MSM female
MSM_female <-  female_mouse.avs_for.analysis %>% filter(strain == "MSM")
mean.MSM.female <- mean(MSM_female$mean_co, na.rm=TRUE)


sans_high_female <- female_mouse.avs_for.analysis %>% filter(strain != "G") %>%  filter(strain != "MSM") %>%  filter(strain != "LEW")
mean.all.other <- mean(sans_high_female$mean_co, na.rm=TRUE)


G.female.diff <- (mean.G.female / mean.all.other)
LEW.female.diff <- (mean.LEW.female / mean.all.other)
MSM.female.diff <- (mean.MSM.female / mean.all.other)
```


```{r male.difference, echo=FALSE}

sans_LowRec_male <- male_mouse.avs_for.analysis %>% filter(species == "M.musculus")  %>%   filter(Rec.group == 0)
#mean(sans_LewRec_male$mean_co)

PWD_male <-  male_mouse.avs_for.analysis %>% filter(strain == "PWD")
#mean(PWD_male$mean_co) / mean(sans_LewRec_male$mean_co)

MSM_male <- male_mouse.avs_for.analysis %>% filter(strain == "MSM")
#mean(MSM_male$mean_co) / mean(sans_LewRec_male$mean_co)

SKIVE_male <-   male_mouse.avs_for.analysis %>% filter(strain == "SKIVE")
#mean(SKIVE_male$mean_co) /  
```


```{r MLH1.HetC.rates, echo=FALSE, warning=FALSE}
#calculate the initial HetC levels from best quality mice and cells (compare both levels (cell and mouse average levels))
#subset MLH1_DF, remove non passing mice (as diagnoised from plots)
#remove quality 5 cells

#outgroups
#SPI
HetC.SPI <- MLH1_data[(MLH1_data$strain == "SPI")&(MLH1_data$quality < 5),]
#unique(HetC.SPI$mouse)
#non-passing mice
SPI.remove.mice <- c("30may18_SPI_f1", "8jun18_SPI_m2")
HetC.SPI <- HetC.SPI[ ! HetC.SPI$mouse %in% SPI.remove.mice, ]
#calq sex mean
SPI.mean.MLH1.obs <- ddply(.data=HetC.SPI, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean(nMLH1.foci),
                 var.MLH1 = var(nMLH1.foci)
)
SPI.HETC.val <- SPI.mean.MLH1.obs$mean.MLH1[1] / SPI.mean.MLH1.obs$mean.MLH1[2]

#SPRET
HetC.SPRET <- MLH1_data[(MLH1_data$strain == "SPRET")&(MLH1_data$quality < 5),]
#unique(HetC.SPRET$mouse)
#non-passing mice
#SPRET.remove.mice <- c("", "")
#HetC.SPRET <- HetC.SPRET[ ! HetC.SPRET$mouse %in% SPRET.remove.mice, ]
#calq sex mean
SPRET.mean.MLH1.obs <- ddply(.data=HetC.SPRET, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean(nMLH1.foci),
                 var.MLH1 = var(nMLH1.foci)
)

SPRET.HETC.val <- SPRET.mean.MLH1.obs$mean.MLH1[1] / SPRET.mean.MLH1.obs$mean.MLH1[2]

#CAROLI
HetC.CAROLI <- MLH1_data[(MLH1_data$strain == "CAROLI")&(MLH1_data$quality < 5),]
#unique(HetC.CAROLI$mouse)
#non-passing mice
#SPRET.remove.mice <- c("", "")
#HetC.SPRET <- HetC.SPRET[ ! HetC.SPRET$mouse %in% SPRET.remove.mice, ]
#calq sex mean
CAROLI.mean.MLH1.obs <- ddply(.data=HetC.CAROLI, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean(nMLH1.foci),
                 var.MLH1 = var(nMLH1.foci)
)

#cast
HetC.CAST <- MLH1_data[(MLH1_data$strain == "CAST")&(MLH1_data$quality < 5),]
#unique(HetC.CAST$mouse)
#non-passing mice
#X.remove.mice <- c("", "")
#HetC.SPRET <- HetC.SPRET[ ! HetC.SPRET$mouse %in% SPRET.remove.mice, ]
#calq sex mean
CAST.mean.MLH1.obs <- ddply(.data=HetC.CAST, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean(nMLH1.foci),
                 var.MLH1 = var(nMLH1.foci)
)
CAST.HETC.val <- CAST.mean.MLH1.obs$mean.MLH1[1] / CAST.mean.MLH1.obs$mean.MLH1[2]

#HMI
HetC.HMI <- MLH1_data[(MLH1_data$strain == "HMI")&(MLH1_data$quality < 5),]
HMI.mean.MLH1.obs <- ddply(.data=HetC.HMI, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean( nMLH1.foci),
                 var.MLH1 = var( nMLH1.foci)
)

#dom

#WSB
HetC.WSB <- MLH1_data[(MLH1_data$strain == "WSB")&(MLH1_data$quality < 5),]
#unique(HetC.WSB$mouse)
#non-passing mice
WSB.remove.mice <- c("8oct14_WSB_f1", "18nov17_WSB_f5", "16jun15_WSB_f3","10mar15_WSB_m2")
HetC.WSB <- HetC.WSB[ ! HetC.WSB$mouse %in% WSB.remove.mice, ]
#calq sex mean
WSB.mean.MLH1.obs <- ddply(.data=HetC.WSB, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean( nMLH1.foci),
                 var.MLH1 = var( nMLH1.foci)
)

WSB.HETC.val <- WSB.mean.MLH1.obs$mean.MLH1[1] / WSB.mean.MLH1.obs$mean.MLH1[2]


#LEW
HetC.LEW <- MLH1_data[(MLH1_data$strain == "LEW")&(MLH1_data$quality < 5),]
unique(HetC.LEW$mouse)
#non-passing mice
LEW.remove.mice <- c("4jan17_LEW_f2")
HetC.LEW <- HetC.WSB[ ! HetC.LEW$mouse %in% LEW.remove.mice, ]

#calq sex mean
LEW.mean.MLH1.obs <- ddply(.data=HetC.LEW, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean( nMLH1.foci),
                 var.MLH1 = var( nMLH1.foci)
)

LEW.HETC.val <- LEW.mean.MLH1.obs$mean.MLH1[1] / LEW.mean.MLH1.obs$mean.MLH1[2]


#G
HetC.G <- MLH1_data[(MLH1_data$strain == "G")&(MLH1_data$quality < 5),]
#unique(HetC.G$mouse)
#non-passing mice
G.remove.mice <- c("8jun15_G_f3","8jun15_G_f4")
HetC.G <- HetC.G[ ! HetC.G$mouse %in% G.remove.mice, ]

#calq sex mean
G.mean.MLH1.obs <- ddply(.data=HetC.G, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean( nMLH1.foci),
                 var.MLH1 = var( nMLH1.foci)
)
G.HETC.val <- G.mean.MLH1.obs$mean.MLH1[1] / G.mean.MLH1.obs$mean.MLH1[2]


#PERC
HetC.PERC <- MLH1_data[(MLH1_data$strain == "PERC")&(MLH1_data$quality < 5),]


#calq sex mean
PERC.mean.MLH1.obs <- ddply(.data=HetC.PERC, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean( nMLH1.foci),
                 var.MLH1 = var( nMLH1.foci)
)
G.HETC.val <- G.mean.MLH1.obs$mean.MLH1[1] / G.mean.MLH1.obs$mean.MLH1[2]

#MUSC

#PWD
HetC.PWD <- MLH1_data[(MLH1_data$strain == "PWD")&(MLH1_data$quality < 5),]
#unique(HetC.PWD$mouse)
#non-passing mice
PWD.remove.mice <- c("1apr15_PWD_f2","8oct14_PWD_f2","8oct14_PWD_f5")
HetC.PWD <- HetC.PWD[ ! HetC.PWD$mouse %in% PWD.remove.mice, ]

#calq sex mean
PWD.mean.MLH1.obs <- ddply(.data=HetC.PWD, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean( nMLH1.foci),
                 var.MLH1 = var( nMLH1.foci)
)
PWD.HETC.val <- PWD.mean.MLH1.obs$mean.MLH1[1] / PWD.mean.MLH1.obs$mean.MLH1[2]

# CZECH
HetC.CZECH <- MLH1_data[(MLH1_data$strain == "CZECH")&(MLH1_data$quality < 5),]
#unique(HetC.CZECH$mouse)

#calq sex mean
CZECH.mean.MLH1.obs <- ddply(.data=HetC.CZECH, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean( nMLH1.foci),
                 var.MLH1 = var( nMLH1.foci)
)
CZECH.HETC.val <- CZECH.mean.MLH1.obs$mean.MLH1[1] / CZECH.mean.MLH1.obs$mean.MLH1[2]


# SKIVE
HetC.SKIVE <- MLH1_data[(MLH1_data$strain == "SKIVE")&(MLH1_data$quality < 5),]
#unique(HetC.SKIVE$mouse)

#calq sex mean
SKIVE.mean.MLH1.obs <- ddply(.data=HetC.SKIVE, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean( nMLH1.foci),
                 var.MLH1 = var( nMLH1.foci)
)

SKIVE.HETC.val <- SKIVE.mean.MLH1.obs$mean.MLH1[1] / SKIVE.mean.MLH1.obs$mean.MLH1[2]

# KAZ
HetC.KAZ <- MLH1_data[(MLH1_data$strain == "KAZ")&(MLH1_data$quality < 5),]
#unique(HetC.KAZ$mouse)

#calq sex mean
KAZ.mean.MLH1.obs <- ddply(.data=HetC.KAZ, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean( nMLH1.foci),
                 var.MLH1 = var( nMLH1.foci)
)
KAZ.HETC.val <- KAZ.mean.MLH1.obs$mean.MLH1[1] / KAZ.mean.MLH1.obs$mean.MLH1[2]


#TOM
HetC.TOM <- MLH1_data[(MLH1_data$strain == "TOM")&(MLH1_data$quality < 5),]
#unique(HetC.TOM$mouse)

#calq sex mean
TOM.mean.MLH1.obs <- ddply(.data=HetC.TOM, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean( nMLH1.foci),
                 var.MLH1 = var( nMLH1.foci)
)
TOM.HETC.val <- TOM.mean.MLH1.obs$mean.MLH1[1] / TOM.mean.MLH1.obs$mean.MLH1[2]

#AST
HetC.AST <- MLH1_data[(MLH1_data$strain == "AST")&(MLH1_data$quality < 5),]
#unique(HetC.AST$mouse)

#calq sex mean
AST.mean.MLH1.obs <- ddply(.data=HetC.AST, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean( nMLH1.foci),
                 var.MLH1 = var( nMLH1.foci)
)
AST.HETC.val <- AST.mean.MLH1.obs$mean.MLH1[1] / AST.mean.MLH1.obs$mean.MLH1[2]
#Molosinus

#MSM
HetC.MSM <- MLH1_data[(MLH1_data$strain == "MSM")&(MLH1_data$quality < 5),]
#unique(HetC.MSM$mouse)

#non-passing mice
MSM.remove.mice <- c("12sep16_MSM_f3")
HetC.MSM <- HetC.MSM[ ! HetC.MSM$mouse %in% MSM.remove.mice, ]

#calq sex mean
MSM.mean.MLH1.obs <- ddply(.data=HetC.MSM, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean( nMLH1.foci),
                 var.MLH1 = var( nMLH1.foci)
)

MSM.HETC.val <- MSM.mean.MLH1.obs$mean.MLH1[1] / MSM.mean.MLH1.obs$mean.MLH1[2]


#MOLF
HetC.MOLF <- MLH1_data[(MLH1_data$strain == "MOLF")&(MLH1_data$quality < 5),]

#non-passing mice
MOLF.remove.mice <- c("27oct18_MOLF_m3")
HetC.MOLF <- HetC.MOLF[ ! HetC.MOLF$mouse %in% MOLF.remove.mice, ]

#calq sex mean
MOLF.mean.MLH1.obs <- ddply(.data=HetC.MOLF, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean( nMLH1.foci),
                 var.MLH1 = var( nMLH1.foci)
)
MOLF.HETC.val <- MOLF.mean.MLH1.obs$mean.MLH1[1] / MOLF.mean.MLH1.obs$mean.MLH1[2]
```



```{r strain.curated.biv, echo=FALSE, warning=FALSE}

strain.BivData.Table <- ddply(mouse.level.BivData_table, c("strain", "sex"), summarise,
                        
                       # Nmice = length(Nmice, na.rm = TRUE),
                        Ncells  = sum(Ncells, na.rm = TRUE), #might not to be sum
                        mean.SC = mean(mean_SC, na.rm =TRUE),
                        var.SC = mean(var, na.rm = TRUE), #mouse average variance of bivalent per mouse
                        #chrm classes
                        av.proportion_0CO = mean(proportion_0CO, na.rm = TRUE),
                        av.proportion_1CO = mean(proportion_1CO, na.rm = TRUE),
                        av.proportion_2CO = mean(proportion_2CO, na.rm = TRUE),
                        av.proportion_3CO = mean(proportion_3CO, na.rm = TRUE),
                       
                        #1CO pos
                        mean.1CO.pos = mean(mean_1CO.pos, na.rm = TRUE),
                        
                        #mean.IFD
                        mean.IFD.ABS = mean(mean_IFD.2CO_ABS, na.rm = TRUE),
                        mean.IFD.PER = mean(mean_IFD.2CO_PER, na.rm = TRUE)
                        )

strain.BivData.Table <- add_subsp(strain.BivData.Table)
strain.BivData.Table <- add_species(strain.BivData.Table)
#not sure the source of the NAs
```


```{r algorithm_performance_stats, echo=FALSE, warning=FALSE}

#calq the mean rate by category

cell.level.BivData_table$pass.rate <- cell.level.BivData_table$nboxes_passed / cell.level.BivData_table$boxs.IDd 

algorithm.stat.mouse <- ddply(cell.level.BivData_table, c("mouse"), summarise,
                        n_obs = length( unique(fileName) ),
                         mean_pass.rate = mean(pass.rate)
                         )

cell.level.BivData_table <- add_sex(cell.level.BivData_table)

algorithm.stat.category <- ddply(cell.level.BivData_table, c("sex", "strain"), summarise,
                        n_obs = length(unique(fileName)),
                        mean_pass.rate = mean(pass.rate)
                         )

```



# MLH1 models


```{r MLH1.MIXED.MODEL.setup, echo=FALSE, warning=FALSE, eval=TRUE}

DF.HetC.MixedModel <- Mouse.Table_HQ[Mouse.Table_HQ$species == "M.musculus",]

DF.HetC.MixedModel.HQ <- DF.HetC.MixedModel

#main df with variables coded as chr, set false for the model
DF.HetC.MixedModel.HQ$subsp <- factor(DF.HetC.MixedModel.HQ$subsp, ordered = FALSE)
DF.HetC.MixedModel.HQ$sex <- factor(DF.HetC.MixedModel.HQ$sex, ordered = FALSE)
DF.HetC.MixedModel.HQ$strain <- factor(DF.HetC.MixedModel.HQ$strain, ordered = FALSE)
DF.HetC.MixedModel.HQ$species <- factor(DF.HetC.MixedModel.HQ$species, ordered = FALSE)

#remove male only strains
remove_strains <- c("TOM","AST","CZECH","CAST","HMI","SPRET","CAROLI", "F1", "PERC", "SPI")

DF.HetC.MixedModel.HQ <- DF.HetC.MixedModel.HQ[! DF.HetC.MixedModel.HQ$strain %in% remove_strains,]

```


Model parameters  


M1 - subsp, sex, (1 | strain)  

M2 - subsp, sex, strain  

M3 - sex, strain  

M4 - strain (sex specific)


```{r MLH1co.lmer.MM1, echo=FALSE, waring=FALSE, message=FALSE, eval=TRUE}

MLH1.MM.M1 <- lmer(mean_co ~ subsp * sex + (1|strain), data= DF.HetC.MixedModel.HQ ) 
MLH1.MM.M1.reduce.sex <- lmer( mean_co ~ subsp  +(1|strain), data=DF.HetC.MixedModel.HQ )
MLH1.MM.M1.reduce.subp <- lmer( mean_co ~ sex  +(1|strain), data=DF.HetC.MixedModel.HQ )

MLH1.MM_interaction <- drop1(MLH1.MM.M1, test="Chisq")$`Pr(Chi)`[2]
MLH1.MM_sex <- anova(MLH1.MM.M1, MLH1.MM.M1.reduce.sex)$`Pr(>Chisq)`[2]
MLH1.MM_subp <- anova(MLH1.MM.M1, MLH1.MM.M1.reduce.subp)$`Pr(>Chisq)`[2]
MLH1.MM_strain <- exactRLRT(MLH1.MM.M1)$p.value 

MLH1.MMlmer_results <- data.frame(sub.sp = MLH1.MM_subp, 
sex.results =  MLH1.MM_sex, 
               interaction.pval = MLH1.MM_interaction,  rand.pval = 
MLH1.MM_strain)

MLH1.MMlmer_results

#write.table(MLH1.MMlmer_results, "~./MLH1_M1_glm.csv", sep=",",row.names = TRUE)

#write_xlsx(MLH1.MMlmer_results, "~./MLH1repo/MLH1_M1_glm.xlsx", col_names = TRUE)

#write.xlsx(MLH1.MMlmer_results, "MLH1_M1_glm.xlsx", col.names = TRUE)
```



**these should be the M1 MLH1 results**
sub.sp      sex.results      interaction.pval     rand.pval
1 0.0011     4.9e-06          0.00021         0


```{r MLH1.glmM2, echo=FALSE, eval=TRUE}

#strain = fixed
MLH1.M2.glm.strain.fixed.full <- glm(mean_co ~ subsp * sex * strain, data=DF.HetC.MixedModel.HQ)

summ.MLH1.M2.glm.strain.fixed.full <- summary(MLH1.M2.glm.strain.fixed.full)

#round(summ$coefficients[,c(1,4)],5 )

#write.table(summ.MLH1.M2.glm.strain.fixed.full$coefficients, "~./MLH1repo/MLH1_M2_glm.csv", sep=",",row.names = TRUE)

#summary.glm(MLH1.M2.glm.strain.fixed.full)$coefficients

#write.xlsx(as.data.frame(summary.glm(MLH1.M2.glm.strain.fixed.full)$coefficients), "MLH1_M2_glm.xlsx", col.names = TRUE, row.names = TRUE)

```


```{r MLH1.glm.M3, echo=FALSE, eval=TRUE}
MLH1.M3.strain.fixed <- glm(mean_co ~ sex * strain, data=DF.HetC.MixedModel.HQ )
summ.MLH1.M3.strain.fixed <- summary(MLH1.M3.strain.fixed)

#round(summ.strain.fixed$coefficients[,c(1,4)],5)

#write.table(summ.MLH1.M3.strain.fixed$coefficients, "~./MLH1repo/MLH1_M3_glm.csv", sep=",",row.names = TRUE)

#write.xlsx(as.data.frame(summary(MLH1.M3.strain.fixed)$coefficients), "MLH1_M3_glm.xlsx", col.names = TRUE, row.names = TRUE)
```


```{r MLH1.Female.specific.glm.M4.M5, echo=FALSE, eval=TRUE}

glm.female.strain.subsp <- glm(mean_co ~ subsp * strain, data= (female_mouse.avs_for.analysis %>% filter(subsp != "Cast") ) )

summry.female.strain.effects <- summary(glm.female.strain.subsp)
#round(summry.female.strain.effects$coefficients[,c(1,4)],5)

#write.table(summry.female.strain.effects$coefficients, "~./MLH1repo/MLH1_M4_female_glm.csv", sep=",",row.names = TRUE)

#write.xlsx(as.data.frame( summry.female.strain.effects$coefficients), "MLH1_M4_female_glm.xlsx", col.names = TRUE, row.names = TRUE)


MLH1.female.spc.glm.M5 <- glm(mean_co ~ strain, data= (female_mouse.avs_for.analysis %>% filter(subsp != "Cast") ) )
sum_MLH1.female.spc.glm.M5 <- summary(MLH1.female.spc.glm.M5)

#write.table(sum_MLH1.female.spc.glm.M5$coefficients, "~./MLH1repo/MLH1_M5_female_glm.csv", sep=",",row.names = TRUE)

#write.xlsx(as.data.frame( sum_MLH1.female.spc.glm.M5$coefficients), "MLH1_M5_female_glm.xlsx", col.names = TRUE, row.names = TRUE)
```


```{r MLH1.Male.specific.glm.M4.M5, echo=FALSE, eval=TRUE}
#M4
MLH1.male.glm.M4 <- glm(mean_co ~ subsp * strain, data=(male_mouse.avs_for.analysis  %>% filter(subsp != "Cast") )   )

sum_MLH1.male.glm.M4 <- summary(MLH1.male.glm.M4)
#PWD, SKIVE, MSM
#8,9,10

#write.table(sum_MLH1.male.glm.M4$coefficients, "~./MLH1repo/MLH1_M4_male_glm.csv", sep=",",row.names = TRUE)

#write.xlsx(as.data.frame(sum_MLH1.male.glm.M4$coefficients), "MLH1_M4_male_glm.xlsx", col.names = TRUE, row.names = TRUE)

#write_xlsx(sum_MLH1.female.spc.glm.M5$coefficients, #"MLH1_M5_female_glm.xlsx", col_names = TRUE)


#M5
MLH1.male.glm.M5 <- glm(mean_co ~ strain, data= (male_mouse.avs_for.analysis  %>% filter(subsp != "Cast") ))
sum_MLH1.male.glm.M5 <- summary(MLH1.male.glm.M5)

#round(lm.male.strain_sum$coefficients[,c(1,4)], 5)

#write.table(sum_MLH1.male.glm.M5$coefficients, "~./MLH1repo/MLH1_M5_male_glm.csv", sep=",",row.names = TRUE)

#write.xlsx(as.data.frame( sum_MLH1.male.glm.M5$coefficients), "MLH1_M5_male_glm.xlsx", col.names = TRUE, row.names = TRUE)

#write_xlsx(sum_MLH1.male.glm.M4.2$coefficients, "~./MLH1repo/MLH1_M5_male_glm.xlsx", col_names = TRUE)
```


# DMC1 Results


```{r DMC1_t.tests1, echo=FALSE, warning=FALSE}

#high vs low group (L)
ttest.HighLow.L.pval <- t.test(DMC1.DF$total.count[( (DMC1.DF$stage == "Early") & ( ( DMC1.DF$strain == "MSM") | (DMC1.DF$strain == "PWD") ) )  ],
               DMC1.DF$total.count[( (DMC1.DF$stage == "Early") & ( ( DMC1.DF$strain == "WSB") | (DMC1.DF$strain == "G") | (DMC1.DF$strain == "KAZ") ) )]    )$p.value
# p-value =  0.002145


#high vs low group (Z)
ttest.HighLow.Z.pval <- t.test(DMC1.DF$total.count[( (DMC1.DF$stage == "Late") & ( ( DMC1.DF$strain == "MSM") | (DMC1.DF$strain == "PWD") ) )  ],
               DMC1.DF$total.count[( (DMC1.DF$stage == "Late") & ( ( DMC1.DF$strain == "WSB") | (DMC1.DF$strain == "G") | (DMC1.DF$strain == "KAZ") ) )]    )$p.value
# p-value = 0.6628


#dom vs musc (L) (2 subsp vs)
ttest.subsp.L <- t.test(DMC1.DF$total.count[(DMC1.DF$subsp == "Dom") & (DMC1.DF$stage == "Early")], DMC1.DF$total.count[(DMC1.DF$subsp == "Musc") & (DMC1.DF$stage == "Early")] )
# p-value = 0.003016

#dom vs musc (Z)
ttest.subsp.Z <- t.test(DMC1.DF$total.count[(DMC1.DF$subsp == "Dom") & (DMC1.DF$stage == "Late")], DMC1.DF$total.count[(DMC1.DF$subsp == "Musc") & (DMC1.DF$stage == "Late")] )
#p-value = 0.09588

#KAZ vs Dom (Z) (only 1 L cell)
ttest.KAZ.Dom.z <- t.test(DMC1.DF$total.count[(DMC1.DF$subsp == "Dom") & (DMC1.DF$stage == "Late")], 
      DMC1.DF$total.count[(DMC1.DF$strain == "KAZ") & (DMC1.DF$stage == "Late")] )

#p-value = 0.004148
#Kaz Z are higher than Dom
```


```{r DMC1.rand.calq1, warning=FALSE, echo=FALSE}

DMC1.mean.obs.L$mean.count.L <- DMC1.mean.obs.L$mean.count
DMC1.mean.obs.Z$mean.count.Z <- DMC1.mean.obs.Z$mean.count

mean.MLH1.obs <- ddply(.data=Mouse.Table_HQ,
                 .(category),
                 summarize, 
                 mean.MLH1 = mean(mean_co),
                 var.MLH1 = var(mean_co)
)


DMC1.target.strains <- subset(mean.MLH1.obs, category == "G male" |
                   category == "WSB male" |
                     category == "KAZ male" |
                  category == "MSM male" |
                    category == "PWD male")

DMC1table <- merge(DMC1.mean.obs.L, DMC1.mean.obs.Z, by="category")

DMC1table.main <- merge(DMC1.target.strains, DMC1table, by="category")

MLH1.DMC1.L_cor <- cor(DMC1table.main$mean.MLH1, DMC1table.main$mean.count.L, method = c("pearson"))#MLH1.DMC1.Z_cor

MLH1.DMC1.Z_cor <- cor(DMC1table.main$mean.MLH1, DMC1table.main$mean.count.Z, method = c("pearson"))#0.2793237
```


```{r DMC1.ratios1, echo=FALSE, warning=FALSE}

##RATIOS
DMC1table.main$MLH1.L_ratio <- DMC1table.main$mean.MLH1/ DMC1table.main$mean.count.L 
DMC1table.main$MLH1.Z_ratio <- DMC1table.main$mean.MLH1 / DMC1table.main$mean.count.Z
  
#colnames(DMC1table.main) <- c("category", "mean.MLH1", "", "", "")

#DMC1.mean.table
DMC1.mean.table.99 <- subset(DMC1table.main, select= -c(var.MLH1,  mean.count.x,  mean.count.y, stage.x, stage.y))

colnames(DMC1.mean.table.99) <- c("category","mean.MLH1","ncells.L","mean.L",
                  "ncells.Z", "mean.Z", "MLH1.L_ratio", "MLH1.Z_ratio")


WSB_DMC1.Z_CO_ratio <-   ( DMC1table.main %>% filter(category == "WSB male") )$mean.count.L / (DMC1table.main %>% filter(category == "WSB male"))$mean.MLH1
  
G_DMC1.Z_CO_ratio <-   ( DMC1table.main %>% filter(category == "G male") )$mean.count.L / (DMC1table.main %>% filter(category == "G male"))$mean.MLH1

MSM_DMC1.Z_CO_ratio <- ( DMC1table.main %>% filter(category == "MSM male") )$mean.count.L / (DMC1table.main %>% filter(category == "MSM male"))$mean.MLH1

PWD_DMC1.Z_CO_ratio <-( DMC1table.main %>% filter(category == "PWD male") )$mean.count.L / (DMC1table.main %>% filter(category == "PWD male"))$mean.MLH1



DMC1table.main$category <- factor(DMC1table.main$category, levels = c("WSB male","G male","KAZ male",               "PWD male","MSM male"), ordered = TRUE )

DMC1table.main <- DMC1table.main[order(DMC1table.main$category),]

#kable(head(DMC1table.main),  caption = "Table X. DMC1 foci counts per cell summary")
#write 


DMC1.Lratio_t.test <- t.test(  (DMC1table.main %>% filter(  ( category == "G male" | category == "WSB male" | category == "KAZ male" ) ) )$MLH1.L_ratio, 
                (DMC1table.main %>% filter(  ( category == "PWD male" | category == "MSM male") ) )$MLH1.L_ratio        )
                               

DMC1.Zratio_t.test <- t.test(  (DMC1table.main %>% filter(  ( category == "G male" | category == "WSB male" | category == "KAZ male" ) ) )$MLH1.Z_ratio, 
                (DMC1table.main %>% filter(  ( category == "PWD male" | category == "MSM male") ) )$MLH1.Z_ratio        )

```


```{r Q1.total.SC_ttests, warning=FALSE, echo=FALSE}


#full group
Q1.tot.SC_t.test_FM <- t.test( ( mouse.total.skel %>% filter(sex == "male") %>% filter(species == "M.musculus") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) )$mean.skel,
                    (mouse.total.skel %>% filter(sex == "female") %>% filter(species == "M.musculus") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ))$mean.skel  ) #<2e-16


#WSB
Q1.tot.SC_t.test_WSB <- t.test( (mouse.total.skel %>% filter(sex == "male") %>% filter(strain =="WSB" ))$mean.skel,
                                (mouse.total.skel %>% filter(sex == "female") %>% filter(strain =="WSB"))$mean.skel)

#LEW
Q1.tot.SC_t.test_LEW <- t.test( (mouse.total.skel %>% filter(sex == "male") %>% filter(strain =="LEW" ))$mean.skel,
                                (mouse.total.skel %>% filter(sex == "female") %>% filter(strain =="LEW"))$mean.skel)

#G
Q1.tot.SC_t.test_G <- t.test( (mouse.total.skel %>% filter(sex == "male") %>% filter(strain =="G" ))$mean.skel,
                                (mouse.total.skel %>% filter(sex == "female") %>% filter(strain =="G"))$mean.skel)

#PWD
Q1.tot.SC_t.test_PWD <- t.test( (mouse.total.skel %>% filter(sex == "male") %>% filter(strain =="PWD" ))$mean.skel,
                                (mouse.total.skel %>% filter(sex == "female") %>% filter(strain =="PWD"))$mean.skel)

#KAZ
Q1.tot.SC_t.test_KAZ <- t.test( (mouse.total.skel %>% filter(sex == "male") %>% filter(strain =="KAZ" ))$mean.skel,
                                (mouse.total.skel %>% filter(sex == "female") %>% filter(strain =="KAZ"))$mean.skel)

#SKIVE
Q1.tot.SC_t.test_SKIVE <- t.test( (mouse.total.skel %>% filter(sex == "male") %>% filter(strain =="SKIVE" ))$mean.skel,
                                (mouse.total.skel %>% filter(sex == "female") %>% filter(strain =="SKIVE"))$mean.skel)

#MSM
Q1.tot.SC_t.test_MSM <- t.test( (mouse.total.skel %>% filter(sex == "male") %>% filter(strain =="MSM" ))$mean.skel,
                                (mouse.total.skel %>% filter(sex == "female") %>% filter(strain =="MSM"))$mean.skel)
```



```{r Q1_SC.biv.short_ttest, echo=FALSE, include=TRUE, warning=FALSE}


Q1_short.SC_t.test.FM <- t.test( ( Short.biv_mouse_table %>% filter(sex == "male") %>% filter(species == "M.musculus") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) )$mean_SC,
                    (Short.biv_mouse_table %>% filter(sex == "female") %>% filter(species == "M.musculus") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ))$mean_SC  ) #<2e-16

# WSB p-value = 0.02 (highest p val)
Q1_short.SC_t.test.WSB <- t.test((Short.biv_mouse_table %>% filter(sex == "male") %>% filter(strain == "WSB") )$mean_SC,
                           (Short.biv_mouse_table %>% filter(sex == "female") %>% filter(strain == "WSB") )$mean_SC)


#G  p-value = 5e-04
Q1_short.SC_t.test.G <- t.test((Short.biv_mouse_table %>% filter(sex == "male") %>% filter(strain == "G") )$mean_SC,
                           (Short.biv_mouse_table %>% filter(sex == "female") %>% filter(strain == "G") )$mean_SC)

#LEW  p-value = 0.002
#Q1_short.SC_t.test.LEW <- t.test((Short.biv_mouse_table %>% filter(sex == "male") %>% filter(strain == #"LEW") )$mean_SC,
#                           (Short.biv_mouse_table %>% filter(sex == "female") %>% filter(strain == "LEW") #)$mean_SC)

#PWD p-value = 0.008
Q1_short.SC_t.test.PWD <- t.test((Short.biv_mouse_table %>% filter(sex == "male") %>% filter(strain == "PWD") )$mean_SC,
                           (Short.biv_mouse_table %>% filter(sex == "female") %>% filter(strain == "PWD") )$mean_SC)

#KAZ p-value = 0.06
Q1_short.SC_t.test.KAZ <- t.test((Short.biv_mouse_table %>% filter(sex == "male") %>% filter(strain == "KAZ") )$mean_SC,
                           (Short.biv_mouse_table %>% filter(sex == "female") %>% filter(strain == "KAZ") )$mean_SC)


#not enough y observations
#SKIVE -- not significant (kinda few )
Q1_short.SC_t.test.SKIVE <- t.test((Short.biv_mouse_table %>% filter(sex == "male") %>% filter(strain == "SKIVE") )$mean_SC,
                   (Short.biv_mouse_table %>% filter(sex == "female") %>% filter(strain == "SKIVE") )$mean_SC)

#MSM -- not enough male measures
#Q1_short.SC_t.test.MSM <- t.test((Short.biv_mouse_table %>% filter(sex == "male") %>% filter(strain == "MSM") )$mean_SC,
#                           (Short.biv_mouse_table %>% filter(sex == "female") %>% filter(strain == "MSM") )$mean_SC)

```



```{r Q1_short_ratios, echo=FALSE, eval=TRUE, warning=FALSE}
#WSB
Q1SC.mus.av.short.biv_DIFF_WSB <- mean( (Short.biv_mouse_table %>% filter(sex == "female") %>% filter(strain == "WSB") )$mean_SC) / mean(  (Short.biv_mouse_table %>% filter(sex == "male") %>% filter(strain == "WSB") )$mean_SC )

#LEW
Q1SC.mus.av.short.biv_DIFF_LEW <- mean( (Short.biv_mouse_table %>% filter(sex == "female") %>% filter(strain == "LEW") )$mean_SC) / mean(  (Short.biv_mouse_table %>% filter(sex == "male") %>% filter(strain == "LEW") )$mean_SC )

#G
Q1SC.mus.av.short.biv_DIFF_G <- mean( (Short.biv_mouse_table %>% filter(sex == "female") %>% filter(strain == "G") )$mean_SC) / mean(  (Short.biv_mouse_table %>% filter(sex == "male") %>% filter(strain == "G") )$mean_SC )

#PWD
Q1SC.mus.av.short.biv_DIFF_PWD <- mean( (Short.biv_mouse_table %>% filter(sex == "female") %>% filter(strain == "PWD") )$mean_SC) / mean(  (Short.biv_mouse_table %>% filter(sex == "male") %>% filter(strain == "PWD") )$mean_SC )

#KAZ
Q1SC.mus.av.short.biv_DIFF_KAZ <- mean( (Short.biv_mouse_table %>% filter(sex == "female") %>% filter(strain == "KAZ") )$mean_SC) / mean(  (Short.biv_mouse_table %>% filter(sex == "male") %>% filter(strain == "KAZ") )$mean_SC )

#SKIVE
Q1SC.mus.av.short.biv_DIFF_SKIVE <- mean( (Short.biv_mouse_table %>% filter(sex == "female") %>% filter(strain == "SKIVE") )$mean_SC) / mean(  (Short.biv_mouse_table %>% filter(sex == "male") %>% filter(strain == "SKIVE") )$mean_SC )

#MSM
Q1SC.mus.av.short.biv_DIFF_MSM <- mean( (Short.biv_mouse_table %>% filter(sex == "female") %>% filter(strain == "MSM") )$mean_SC) / mean(  (Short.biv_mouse_table %>% filter(sex == "male") %>% filter(strain == "MSM") )$mean_SC )

#this bivData ratio is the same as mouse average
Q1SC.BivData.short.biv_DIFF_MSM <- mean( (Short.biv_mouse_table %>% filter(sex == "female") %>% filter(strain == "MSM") )$chromosomeLength) / mean(  (Short.biv_mouse_table %>% filter(sex == "male") %>% filter(strain == "MSM") )$chromosomeLength )

```


## Total sc models


```{r Q1.total.SC_M1, echo=FALSE}
mouse.total.skel$subsp <- factor(mouse.total.skel$subsp, ordered = FALSE)
mouse.total.skel$sex <- factor(mouse.total.skel$sex, ordered = FALSE)
mouse.total.skel$strain <- factor(mouse.total.skel$strain, ordered = FALSE)
mouse.total.skel$species <- factor(mouse.total.skel$species, ordered = FALSE)

#mouse.total.skel
Q1.lmer_totSC_M1 <- lmer(mean.skel ~ subsp * sex + (1|strain), data= ( mouse.total.skel %>% filter(species == "M.musculus") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) %>% filter(strain !=  "TOM" ))  )

Q1.lmer_totSC_M1_R.sex <- lmer(mean.skel ~ subsp + (1|strain), data=( mouse.total.skel %>% filter(species == "M.musculus") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) %>% filter(strain !=  "TOM" ) ))

Q1.lmer_totSC_M1_R.subsp <- lmer(mean.skel ~ sex + (1|strain), data=( mouse.total.skel %>% filter(species == "M.musculus") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) %>% filter(strain !=  "TOM" ) ) ) 

#as.data.frame(round(summary(Q1.lmer_SCLength_1CO_M1)$coefficients, 6))

Q1.lmer_totSC_M1_sex <- anova(Q1.lmer_totSC_M1, Q1.lmer_totSC_M1_R.sex)$`Pr(>Chisq)`[2]
Q1.lmer_totSC_M1_subsp <- anova(Q1.lmer_totSC_M1, Q1.lmer_totSC_M1_R.subsp)$`Pr(>Chisq)`[2]
Q1.lmer_totSC_M1_int <- drop1(Q1.lmer_totSC_M1, test="Chisq")$`Pr(Chi)`[2]
Q1.lmer_totSC_M1_strain <- exactRLRT(Q1.lmer_totSC_M1)$p.value

Q1.lmer_totSC_M1_results <- data.frame(sub.sp = Q1.lmer_totSC_M1_subsp, 
sex.results =  Q1.lmer_totSC_M1_sex, 
               interaction.pval = Q1.lmer_totSC_M1_int,
rand.pval = Q1.lmer_totSC_M1_strain)


#write.table(Q1.lmer_totSC_M1_results, "~./MLH1repo/TotalSC_Q1_M1.csv", sep=",",row.names = TRUE)

#write_xlsx(Q1.lmer_totSC_M1_results, "~./MLH1repo/TotalSC_Q1_M1.xlsx", col_names = TRUE)

#write.xlsx(Q1.lmer_totSC_M1_results, "TotalSC_Q1_M1.xlsx", col.names = TRUE)
```


```{r Q1.glm_totalSC_M2, echo=FALSE, message=FALSE}
#mouse.total.skel

mouse.total.skel$subsp <- factor(mouse.total.skel$subsp, ordered = FALSE)
mouse.total.skel$sex <- factor(mouse.total.skel$sex, ordered = FALSE)
mouse.total.skel$strain <- factor(mouse.total.skel$strain, ordered = FALSE)
mouse.total.skel$species <- factor(mouse.total.skel$species, ordered = FALSE)


Q1.glm_totSC_M2 <- glm(mean.skel ~ subsp*strain * sex, data=  (mouse.total.skel %>% filter(species == "M.musculus") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) %>% filter(strain !=  "TOM" ) )  )

sum.Q1.glm_totSC_M2 <- summary(Q1.glm_totSC_M2)
#sum.Q1.glm_totSC_M2$coefficients[,c(1,4)][8,]

#sex most sig  #subsp
#straing G, LEW
#mol * sex
#G * sex

#write.table(sum.Q1.glm_totSC_M2$coefficients, "~./MLH1repo/TotalSC_Q1_M2.csv", sep=",",row.names = TRUE)

#write.xlsx(as.data.frame(summary.glm(Q1.glm_totSC_M2)$coefficients), "TotalSC_Q1_M2.xlsx", col.names = TRUE, row.names = TRUE)

#write_xlsx(sum.Q1.glm_totSC_M2$coefficients, "~./MLH1repo/TotalSC_Q1_M2.xlsx", col_names = TRUE)
```


```{r Q1.glm_totalSC_M3, echo=FALSE, message=FALSE}

mouse.total.skel$subsp <- factor(mouse.total.skel$subsp, ordered = FALSE)
mouse.total.skel$sex <- factor(mouse.total.skel$sex, ordered = FALSE)
mouse.total.skel$strain <- factor(mouse.total.skel$strain, ordered = FALSE)
mouse.total.skel$species <- factor(mouse.total.skel$species, ordered = FALSE)

Q1.glm_totSC_M3 <- glm(mean.skel ~ strain * sex, data=  (mouse.total.skel %>% filter(species == "M.musculus") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) %>% filter(strain !=  "TOM" ) ) )

sum.Q1.glm_totSC_M3 <- summary(Q1.glm_totSC_M3)
#sex most significant, 
#PWD more sig

#G, LEW, MSM, SKIVE, KAZ,  
#G*male, MSM*male

#LOT OF SIGNIFICant strain effects in this model
#write.table(sum.Q1.glm_totSC_M3$coefficients, "~./MLH1repo/TotalSC_Q1_M3.csv", sep=",",row.names = TRUE)


#write.xlsx(  as.data.frame( summary(sum.Q1.glm_totSC_M3)$coefficients ), "TotalSC_Q1_M3.xlsx", col.names = TRUE, row.names = TRUE)

#write.xlsx(as.data.frame(summary.glm(Q1.glm_totSC_M3)$coefficients), "TotalSC_Q1_M3.xlsx", col.names = TRUE, row.names = TRUE)

#write_xlsx(sum.Q1.glm_totSC_M3$coefficients, "~./MLH1repo/TotalSC_Q1_M3.xlsx", col_names = TRUE)
```


```{r Q1_SC_short.M1, echo=FALSE}

Short.biv_mouse_table$subsp <- factor(Short.biv_mouse_table$subsp, ordered = FALSE)
Short.biv_mouse_table$sex <- factor(Short.biv_mouse_table$sex, ordered = FALSE)
Short.biv_mouse_table$strain <- factor(Short.biv_mouse_table$strain, ordered = FALSE)
Short.biv_mouse_table$species <- factor(Short.biv_mouse_table$species, ordered = FALSE)

Q1.lmer_short_M1 <- lmer(mean_SC ~ subsp * sex + (1|strain), data= ( Short.biv_mouse_table %>% filter(species == "M.musculus") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) %>% filter(strain !=  "TOM" ) ) )

Q1.lmer_short_M1_R.sex <- lmer(mean_SC ~ subsp + (1|strain), data= ( Short.biv_mouse_table %>%  filter(species == "M.musculus") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) %>% filter(strain !=  "TOM" ) ) )

Q1.lmer_short_M1_R.subsp <- lmer(mean_SC ~ sex + (1|strain), data= ( Short.biv_mouse_table %>% filter(species == "M.musculus") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" )  %>% filter(strain !=  "TOM" ) )  ) 


Q1.lmer_short_M1_sex <- anova(Q1.lmer_short_M1, Q1.lmer_short_M1_R.sex)$`Pr(>Chisq)`[2]

Q1.lmer_short_M1_subsp <- anova(Q1.lmer_short_M1, Q1.lmer_short_M1_R.subsp)$`Pr(>Chisq)`[2]

Q1.lmer_short_M1_int <- drop1(Q1.lmer_short_M1, test="Chisq")$`Pr(Chi)`[2]

Q1.lmer_short_M1_strain <- exactRLRT(Q1.lmer_short_M1)$p.value


Q1.lmer_short_M1_results <- data.frame(sub.sp = Q1.lmer_short_M1_subsp, 
sex.results =  Q1.lmer_short_M1_sex, 
               interaction.pval = Q1.lmer_short_M1_int,
rand.pval = Q1.lmer_short_M1_strain)


#write.table(Q1.lmer_short_M1_results, "~./MLH1repo/ShortSC_Q1_M1.csv", sep=",",row.names = TRUE)

#write_xlsx(Q1.lmer_short_M1_results, "~./MLH1repo/ShortSC_Q1_M1.xlsx", col_names = TRUE)
#write.xlsx(Q1.lmer_short_M1_results, "ShortSC_Q1_M1.xlsx", col.names = TRUE)

```


```{r Q1.SC_short_M2, echo=FALSE, warning=FALSE, message=FALSE}

Short.biv_mouse_table$subsp <- factor(Short.biv_mouse_table$subsp, ordered = FALSE)
Short.biv_mouse_table$sex <- factor(Short.biv_mouse_table$sex, ordered = FALSE)
Short.biv_mouse_table$strain <- factor(Short.biv_mouse_table$strain, ordered = FALSE)

Q1.glm_short.SC_M2 <- glm(mean_SC ~ subsp * strain * sex, data= ( Short.biv_mouse_table %>% filter(species == "M.musculus") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) %>% filter(strain !=  "TOM" ) ) )

summ.Q1.glm_short.SC_M2 <- summary(Q1.glm_short.SC_M2)
#summ.Q1.glm_short.SC_M2$coefficients[,c(1,4)][8,]

#sex most sig
#skive, slightly sig

#write.table(summ.Q1.glm_short.SC_M2$coefficients, "~./MLH1repo/ShortSC_Q1_M2.csv", sep=",",row.names = TRUE)

#write_xlsx(summ.Q1.glm_short.SC_M2$coefficients, "~./MLH1repo/ShortSC_Q1_M2.xlsx", col_names = TRUE)

#write.xlsx( as.data.frame( summ.Q1.glm_short.SC_M2$coefficients) , "ShortSC_Q1_M2.xlsx", col.names = TRUE, row.names = TRUE)
```


```{r Q1.glm_short.SC_M3, echo=FALSE, message=FALSE}

Short.biv_mouse_table$subsp <- factor(Short.biv_mouse_table$subsp, ordered = FALSE)
Short.biv_mouse_table$sex <- factor(Short.biv_mouse_table$sex, ordered = FALSE)
Short.biv_mouse_table$strain <- factor(Short.biv_mouse_table$strain, ordered = FALSE)

Q1.glm_short.SC_M3 <- glm(mean_SC ~ strain * sex, data= ( Short.biv_mouse_table %>% filter(species == "M.musculus") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) %>% filter(strain !=  "TOM" ) )  )

#summary(Q1.glm_short.SC_M3)
summ.Q1.glm_short.SC_M3 <- summary(Q1.glm_short.SC_M3)

#round(summ.Q1.glm_short.SC_M3$coefficients[,c(1,4)],5)
#sex male very sig -- only sig
#sum.Q1.glm_totSC_M2$coefficients[,c(1,4)][8,]
#SKIVE * male

#write.table(summ.Q1.glm_short.SC_M3$coefficients, "~./MLH1repo/ShortSC_Q1_M3.csv", sep=",",row.names = TRUE)

#write.xlsx(as.data.frame( summ.Q1.glm_short.SC_M3$coefficients), "ShortSC_Q1_M3.xlsx", col.names = TRUE, row.names = TRUE)

```


```{r Female.shortBivalent.M4.M5, echo=FALSE}
#these M4 and M5 could be run for short and Long
Short.biv_mouse_table$subsp <- factor(Short.biv_mouse_table$subsp, ordered = FALSE)
Short.biv_mouse_table$sex <- factor(Short.biv_mouse_table$sex, ordered = FALSE)
Short.biv_mouse_table$strain <- factor(Short.biv_mouse_table$strain, ordered = FALSE)
#mean_SC
#Short.biv_mouse_table

#M4
ShortBiv.female.glm_M4 <- glm(mean_SC ~ subsp * strain, data= (Short.biv_mouse_table %>% filter(subsp != "Cast") %>% filter(species == "M.musculus") %>% filter(sex == "female") ) )
sum.ShortBiv.female.glm_M4 <- summary(ShortBiv.female.glm_M4)
write.xlsx(as.data.frame( sum.ShortBiv.female.glm_M4$coefficients), "ShortBiv.female.glm_M4.xlsx", col.names = TRUE, row.names = TRUE)

#M5
ShortBiv.female.glm_M5 <- glm(mean_SC ~ strain, data= (Short.biv_mouse_table %>% filter(subsp != "Cast") %>% filter(species == "M.musculus") %>% filter(sex == "female") ) )
sum.ShortBiv.female.glm_M5 <- summary(ShortBiv.female.glm_M5)
write.xlsx(as.data.frame( sum.ShortBiv.female.glm_M5$coefficients), "ShortBiv.female.glm_M5.xlsx", col.names = TRUE, row.names = TRUE)

```



```{r male.ShortBiv.M4.M5, echo=FALSE}
#M4
ShortBiv.male.glm_M4 <- glm(mean_SC ~ subsp * strain, data= (Short.biv_mouse_table %>% filter(subsp != "Cast") %>% filter(species == "M.musculus") %>% filter(sex == "male") ) )
sum.ShortBiv.male.glm_M4 <- summary(ShortBiv.male.glm_M4)
write.xlsx(as.data.frame( sum.ShortBiv.male.glm_M4$coefficients), "ShortBiv.male.glm_M4.xlsx", col.names = TRUE, row.names = TRUE)

#M5
ShortBiv.male.glm_M5 <- glm(mean_SC ~ strain, data= (Short.biv_mouse_table %>% filter(subsp != "Cast") %>% filter(species == "M.musculus") %>% filter(sex == "male") ) )
sum.ShortBiv.male.glm_M5 <- summary(ShortBiv.male.glm_M5)
write.xlsx(as.data.frame( sum.ShortBiv.male.glm_M5$coefficients), "ShortBiv.male.glm_M5.xlsx", col.names = TRUE, row.names = TRUE)
```


```{r Q1.SC.Q12, echo=FALSE}

#make comparisons for the high quality cells
#get Q12 cells from MLH1.merge.Skel
#calq the mouse averages

Total.SC_DF$quality <- as.numeric(Total.SC_DF$quality)

totSC_Q12_mouse.av.table <- ddply(.data= Total.SC_DF %>% filter(quality < 3), 
                 .(mouse),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                # mean.MLH1 = mean( nMLH1.foci, na.rm = TRUE),
                # var.MLH1 = var( nMLH1.foci, na.rm = TRUE),
                 
                 mean.skel = mean(skel_size, na.rm = TRUE),
                #se for skel
                
                 mean.bin =  mean(bin_size, na.rm = TRUE)
                 
)

totSC_Q12_mouse.av.table <- add_strain(totSC_Q12_mouse.av.table)
totSC_Q12_mouse.av.table <- add_sex(totSC_Q12_mouse.av.table)
totSC_Q12_mouse.av.table <- add_category(totSC_Q12_mouse.av.table)
totSC_Q12_mouse.av.table <- add_subsp(totSC_Q12_mouse.av.table)
totSC_Q12_mouse.av.table <- add_species(totSC_Q12_mouse.av.table)

#unorder the factors
totSC_Q12_mouse.av.table$subsp <- factor(totSC_Q12_mouse.av.table$subsp, ordered = FALSE)
totSC_Q12_mouse.av.table$sex <- factor(totSC_Q12_mouse.av.table$sex, ordered = FALSE)
totSC_Q12_mouse.av.table$strain <- factor(totSC_Q12_mouse.av.table$strain, ordered = FALSE)
totSC_Q12_mouse.av.table$species <- factor(totSC_Q12_mouse.av.table$species, ordered = FALSE)

#add rec group
totSC_Q12_mouse.av.table$Rec.group <- ifelse(grepl("PWD male", totSC_Q12_mouse.av.table$category), 1, 
                              ifelse(grepl("MSM male", totSC_Q12_mouse.av.table$category), 1,
                                ifelse(grepl("SKIVE male", totSC_Q12_mouse.av.table$category), 1, 0)))

#REMOVE JUVI mice
tot.SC.Q12_juvi.male <- totSC_Q12_mouse.av.table[totSC_Q12_mouse.av.table$mouse  %in% juvi_mice.list, ]
totSC_Q12_mouse.av.table <- totSC_Q12_mouse.av.table[! totSC_Q12_mouse.av.table$mouse  %in% juvi_mice.list, ] 



totSC_Q12_strain.av.table <- ddply(.data= Total.SC_DF %>% filter(quality < 3), 
                 .(strain, sex),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                # mean.MLH1 = mean( nMLH1.foci, na.rm = TRUE),
                # var.MLH1 = var( nMLH1.foci, na.rm = TRUE),
                 
                 mean.skel = mean(skel_size, na.rm = TRUE),
                #se for skel
                
                 mean.bin =  mean(bin_size, na.rm = TRUE)
                 
)
totSC_Q12_strain.av.table <- add_subsp(totSC_Q12_strain.av.table)
totSC_Q12_strain.av.table <- add_species(totSC_Q12_strain.av.table)

#unorder the factors
totSC_Q12_strain.av.table$subsp <- factor(totSC_Q12_strain.av.table$subsp, ordered = FALSE)
totSC_Q12_strain.av.table$sex <- factor(totSC_Q12_strain.av.table$sex, ordered = FALSE)
totSC_Q12_strain.av.table$strain <- factor(totSC_Q12_strain.av.table$strain, ordered = FALSE)
totSC_Q12_strain.av.table$species <- factor(totSC_Q12_strain.av.table$species, ordered = FALSE)

```


```{r Q1.SC_showQ12Tot.SC, echo=FALSE, warning=FALSE}

Q12.Tot.SC_mouse.av_Dom <- ggplot(data= totSC_Q12_mouse.av.table %>% filter(subsp == "Dom"), aes(y = mean.skel, x=mouse, color=strain))+ geom_point()+scale_color_manual(values=colors_of_strains)+
  facet_wrap(~sex, scales="free", ncol = 3)+ 
  
  geom_hline(data =totSC_Q12_strain.av.table %>% filter(subsp == "Dom"), aes(yintercept=mean.skel) )+
  
  theme(axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank())+  ylim(c(1000,2600 ))+ggtitle("Mouse av. Q12 total SC area")

#Q12.Tot.SC_mouse.av_Dom
#Tot.SC_mouse.av_Dom

Q12.Tot.SC_mouse.av_Musc <- ggplot(data= totSC_Q12_mouse.av.table %>% filter(subsp == "Musc"), aes(y = mean.skel, x=mouse, color=strain))+ geom_point()+scale_color_manual(values=colors_of_strains)+
  facet_wrap(~sex, scales="free", ncol = 3)+ 
  
  geom_hline(data =totSC_Q12_strain.av.table %>% filter(subsp == "Musc"), aes(yintercept=mean.skel) )+
  
  theme(axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank())+  ylim(c(1000,3000 ))+ggtitle("Mouse av. Q12 total SC area")

#Q12.Tot.SC_mouse.av_Musc
#Tot.SC_mouse.av_Musc

Q12.Tot.SC_mouse.av_Mol <- ggplot(data= totSC_Q12_mouse.av.table %>% filter(subsp == "Mol"), aes(y = mean.skel, x=mouse, color=strain))+ geom_point()+scale_color_manual(values=colors_of_strains)+
  facet_wrap(~sex, scales="free", ncol = 3)+ 
  
  geom_hline(data =totSC_Q12_strain.av.table %>% filter(subsp == "Mol"), aes(yintercept=mean.skel) )+
  
  theme(axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank())+  ylim(c(1000,3000 ))+ggtitle("Mouse av. Q12 total SC area")
```


# Chromosome Class Proportions


```{r chrm_prop_data, echo=FALSE, warning=FALSE}


chrm.class.DF = read.csv("~./MeioticRecombSexualDimorphism/data/ChrmClassProportions.csv", header = TRUE)

#this excel file is ~100 cells (10 per category) where I manually verified the number of chrm classes.

chrm.class.DF$fileName <- (chrm.class.DF$Original.Name)
chrm.class.DF <- add_mouse(chrm.class.DF)
chrm.class.DF <- add_strain(chrm.class.DF)
chrm.class.DF <- add_sex(chrm.class.DF)
chrm.class.DF <- add_category(chrm.class.DF)


#table(chrm.class.DF$category)
#str(chrm.class.DF)

#summarize by category
proportion_stats_category  <- ddply(.data=chrm.class.DF, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                  tot_biv  = sum(biv.sum.check,  na.rm = TRUE),

                 n0CO = sum(n0CO, na.rm = TRUE),
                  n1CO = sum(n1CO,na.rm = TRUE),
                  n2CO = sum(n2CO,na.rm = TRUE),
                  n3CO = sum(n3CO,na.rm = TRUE),
                  n4CO = sum(n4CO,na.rm = TRUE),
                 
                 per0CO = sum(n0CO) / tot_biv,                 
                 per1CO= sum(n1CO)/ tot_biv,
                 per2CO= sum(n2CO)/ tot_biv,
                 per3CO= sum(n3CO)/ tot_biv,
                 per4CO= sum(n4CO)/ tot_biv,
                 
                 mean.MLH1.foci = mean(MLH1.sum.check),
                 mean.MLH1.foci2 = mean(nMLH1.foci),
                 meanQ = mean(quality)

)


#write.table(proportion_stats_category, "~./MLH1repo/prop_category.csv", sep=",", row.names = FALSE)
```


```{r plot.chrm.prop.melt, echo=FALSE, warning=FALSE}

#melt version used for making figure
melt.Chrm.Prop.table = read.csv("~./MeioticRecombSexualDimorphism/data/ChrmClassProportions_melt.csv", header = TRUE)


melt.Chrm.Prop.table <- melt.Chrm.Prop.table[c(1:5)]

#add the subsps
melt.Chrm.Prop.table$strain<- factor(melt.Chrm.Prop.table$strain, levels =c("LEW",
                      "WSB","G", "TOM","AST","KAZ", "SKIVE","PWD","MSM", "MOLF"), order=T )

melt.Chrm.Prop.table <- with(melt.Chrm.Prop.table, melt.Chrm.Prop.table[order(strain),])

chrm.class.barplot <- ggplot(data = melt.Chrm.Prop.table, aes(y = value, x = strain, fill=as.factor(type)) ) + geom_col(position = "dodge")+facet_grid(sex~strain, scales = "free")+ggtitle("Chrm Proportions from Hand Measured Data")+ylim(c(0,1))+theme(legend.position="none")

#chrm.class.barplot
```


```{r test.Chrm.Prop, echo=FALSE, eval=TRUE, warning=FALSE}

#prop.test(x, y)  x number of successes, y total  
#strain sums of n

Chrm.prop_strain_table <- ddply(mouse.level.BivData_table, c("strain","sex"), summarise,
                  
                  nbiv = sum(tot.biv ),              
                 n0CO = sum(n0CO ),
                  n1CO = sum(n1CO ),
                 n2CO = sum(n2CO ),
                  n3CO = sum(n3CO ),
                 n4CO = sum(n4CO )
                          )

Chrm.prop_strain_table <- add_subsp(Chrm.prop_strain_table)

for(g in 1:length(Chrm.prop_strain_table$nbiv)){
  
  Chrm.prop_strain_table$sum2[g] <- sum(c(Chrm.prop_strain_table$n0CO[g],
                                     Chrm.prop_strain_table$n1CO[g],
                                     Chrm.prop_strain_table$n2CO[g],
                                     Chrm.prop_strain_table$n3CO[g] ))  
}

Chrm.prop_strain_table$dcheck <- Chrm.prop_strain_table$nbiv - Chrm.prop_strain_table$sum2
#there are still some wacky entries -- but much fewer than before

chrm.prop.strain.female <-  Chrm.prop_strain_table %>%  filter(sex == "female")

female.0CO.prop.test <- prop.test(chrm.prop.strain.female$n0CO, chrm.prop.strain.female$sum2 )
female.1CO.prop.test <- prop.test(chrm.prop.strain.female$n1CO, chrm.prop.strain.female$sum2 )
female.2CO.prop.test <- prop.test(chrm.prop.strain.female$n2CO, chrm.prop.strain.female$sum2 )
#the pvalues for 0CO are not sig
#the p values for 1CO and 2CO are sig

#seperate by subsp
chrm.prop.female.dom <-  chrm.prop.strain.female %>%  filter(subsp == "Dom")
chrm.prop.female.musc <-  chrm.prop.strain.female %>%  filter(subsp == "Musc")
chrm.prop.female.mol <-  chrm.prop.strain.female %>%  filter(subsp == "Mol")

Dom_female.0CO.prop.test <- prop.test(chrm.prop.female.dom$n0CO, chrm.prop.female.dom$sum2 )
Dom_female.1CO.prop.test <- prop.test(chrm.prop.female.dom$n1CO, chrm.prop.female.dom$sum2 )
Dom_female.2CO.prop.test <- prop.test(chrm.prop.female.dom$n2CO, chrm.prop.female.dom$sum2 )
Dom_female.3CO.prop.test <- prop.test(chrm.prop.female.dom$n3CO, chrm.prop.female.dom$sum2 )
#WSB has fewer 2COs than other 3 strains

Musc_female.0CO.prop.test <- prop.test(chrm.prop.female.musc$n0CO, chrm.prop.female.musc$sum2 )
Musc_female.1CO.prop.test <- prop.test(chrm.prop.female.musc$n1CO, chrm.prop.female.musc$sum2 )
Musc_female.2CO.prop.test <- prop.test(chrm.prop.female.musc$n2CO, chrm.prop.female.musc$sum2 )
#KAZ has slightly more 1CO than the other two

chrm.prop.female.high <-  chrm.prop.strain.female %>%  filter(strain == "G" | strain == "LEW")

high_female.0CO.prop.test <- prop.test(chrm.prop.female.high$n0CO, chrm.prop.female.high$sum2 )
high_female.1CO.prop.test <- prop.test(chrm.prop.female.high$n1CO, chrm.prop.female.high$sum2 )
high_female.2CO.prop.test <- prop.test(chrm.prop.female.high$n2CO, chrm.prop.female.high$sum2 )


#Low.female.G.LEW.
chrm.prop.female.low <-  chrm.prop.strain.female %>%  filter(strain != "G" | strain != "LEW")

low_female.0CO.prop.test <- prop.test(chrm.prop.female.low$n0CO, chrm.prop.female.low$sum2 )
low_female.1CO.prop.test <- prop.test(chrm.prop.female.low$n1CO, chrm.prop.female.low$sum2 )
low_female.2CO.prop.test <- prop.test(chrm.prop.female.low$n2CO, chrm.prop.female.low$sum2 )

#all females
chrm.prop.strain.male <-  Chrm.prop_strain_table %>%  filter(sex == "male")
male.0CO.prop.test <- prop.test(chrm.prop.strain.male$n0CO, chrm.prop.strain.male$sum2 )

male.1CO.prop.test <- prop.test(chrm.prop.strain.male$n1CO, chrm.prop.strain.male$sum2 )
male.2CO.prop.test <- prop.test(chrm.prop.strain.male$n2CO, chrm.prop.strain.male$sum2 )
#the pvals for these 3 class are sig dif

#seperate by subsp
chrm.prop.male.dom <-  chrm.prop.strain.male %>%  filter(subsp == "Dom")
chrm.prop.male.musc <-  chrm.prop.strain.male %>%  filter(subsp == "Musc")
chrm.prop.male.mol <-  chrm.prop.strain.male %>%  filter(subsp == "Mol")

Dom_male.0CO.prop.test <- prop.test(chrm.prop.male.dom$n0CO, chrm.prop.male.dom$nbiv )
Dom_male.1CO.prop.test <- prop.test(chrm.prop.male.dom$n1CO, chrm.prop.male.dom$nbiv )
Dom_male.2CO.prop.test <- prop.test(chrm.prop.male.dom$n2CO, chrm.prop.male.dom$nbiv )
#non of the Dom proportions are different

Musc_male.0CO.prop.test <- prop.test(chrm.prop.male.musc$n0CO, chrm.prop.male.musc$nbiv )
Musc_male.1CO.prop.test <- prop.test(chrm.prop.male.musc$n1CO, chrm.prop.male.musc$nbiv )
Musc_male.2CO.prop.test <- prop.test(chrm.prop.male.musc$n2CO, chrm.prop.male.musc$nbiv )
#all v different

Mol_male.0CO.prop.test <- prop.test(chrm.prop.male.mol$n0CO, chrm.prop.male.mol$nbiv )
Mol_male.1CO.prop.test <- prop.test(chrm.prop.male.mol$n1CO, chrm.prop.male.mol$nbiv )
Mol_male.2CO.prop.test <- prop.test(chrm.prop.male.mol$n2CO, chrm.prop.male.mol$nbiv )


#high vs low
chrm.prop.strain.male$Rec.group <- ifelse(grepl("PWD", chrm.prop.strain.male$strain), 1, 
                              ifelse(grepl("MSM", chrm.prop.strain.male$strain), 1,
                                 ifelse(grepl("SKIVE", chrm.prop.strain.male$strain), 1, 0)))

chrm.prop.male.low <-  chrm.prop.strain.male %>%  filter(Rec.group == 0)
chrm.prop.male.low2 <-  chrm.prop.strain.male  %>%  filter(Rec.group == 0 | strain == "SKIVE") #cool this worked


chrm.prop.male.high2 <-  chrm.prop.strain.male %>%  filter(Rec.group == 1) %>%  filter(strain != "SKIVE")
chrm.prop.male.high1 <-  chrm.prop.strain.male %>%  filter(Rec.group == 1)


Low_male.0CO.prop.test <- prop.test(chrm.prop.male.low$n0CO, chrm.prop.male.low$nbiv )
Low_male.1CO.prop.test <- prop.test(chrm.prop.male.low$n1CO, chrm.prop.male.low$nbiv )
Low_male.2CO.prop.test <- prop.test(chrm.prop.male.low$n2CO, chrm.prop.male.low$nbiv )
#the low strains do vary slightly in their 1CO and 2CO proportions

#includes SKIVE
Low2_male.0CO.prop.test <- prop.test(chrm.prop.male.low2$n0CO, chrm.prop.male.low2$nbiv )
Low2_male.1CO.prop.test <- prop.test(chrm.prop.male.low2$n1CO, chrm.prop.male.low2$nbiv )
Low2_male.2CO.prop.test <- prop.test(chrm.prop.male.low2$n2CO, chrm.prop.male.low2$nbiv )
#all very sig p values


High2_male.0CO.prop.test <-prop.test(chrm.prop.male.high2$n0CO,chrm.prop.male.high2$nbiv )
High2_male.1CO.prop.test <- prop.test(chrm.prop.male.high2$n1CO,chrm.prop.male.high2$nbiv )
High2_male.2CO.prop.test <- prop.test(chrm.prop.male.high2$n2CO,chrm.prop.male.high2$nbiv )
#these proportions are v different

#no SKIVE
High1_male.0CO.prop.test <- prop.test(chrm.prop.male.high1$n0CO, chrm.prop.male.high1$nbiv )
High1_male.1CO.prop.test <- prop.test(chrm.prop.male.high1$n1CO, chrm.prop.male.high1$nbiv )
High1_male.2CO.prop.test <- prop.test(chrm.prop.male.high1$n2CO, chrm.prop.male.high1$nbiv )
#MSM and PWD only slightly sig dif for 2CO

#MSM-MOLF
MSM.MOLF.0CO.prop.test <- prop.test( (chrm.prop.strain.male %>% filter(subsp == "Mol") )$n0CO, (chrm.prop.strain.male %>% filter(subsp == "Mol"))$nbiv  )

MSM.MOLF.1CO.prop.test <- prop.test( (chrm.prop.strain.male %>% filter(subsp == "Mol") )$n1CO, (chrm.prop.strain.male %>% filter(subsp == "Mol"))$nbiv  )

MSM.MOLF.2CO.prop.test <- prop.test( (chrm.prop.strain.male %>% filter(subsp == "Mol") )$n2CO, (chrm.prop.strain.male %>% filter(subsp == "Mol"))$nbiv  ) 
 
#PWD-KAZ
PWD.KAZ.0CO.prop.test <- prop.test( (chrm.prop.strain.male %>% filter( (strain == "PWD") | strain == "KAZ") )$n0CO, (chrm.prop.strain.male %>% filter(strain == "PWD" | strain == "KAZ") )$nbiv )

PWD.KAZ.1CO.prop.test <- prop.test( (chrm.prop.strain.male %>% filter( (strain == "PWD") | strain == "KAZ") )$n1CO, (chrm.prop.strain.male %>% filter(strain == "PWD" | strain == "KAZ") )$nbiv )

PWD.KAZ.2CO.prop.test <- prop.test( (chrm.prop.strain.male %>% filter( (strain == "PWD") | strain == "KAZ") )$n2CO, (chrm.prop.strain.male %>% filter(strain == "PWD" | strain == "KAZ") )$nbiv )

#PWD-MSM
PWD.MSM.2CO.prop.test <- prop.test( (chrm.prop.strain.male %>% filter( (strain == "PWD") | strain == "MSM") )$n2CO, (chrm.prop.strain.male %>% filter(strain == "PWD" | strain == "MSM") )$nbiv )
```


# Q1 CO pos


```{r CO.positions.figs, echo=FALSE, include=FALSE, warning=FALSE}

#main figure of density plots
MELT_Curated_BivData <- add_sex(MELT_Curated_BivData)
MELT_Curated_BivData <- add_strain(MELT_Curated_BivData)
MELT_Curated_BivData <- add_subsp(MELT_Curated_BivData)#subsp, needs strain

#clean up all the non 1 to 4 hand.foci counts
MELT_Curated_BivData.1CO <- MELT_Curated_BivData[MELT_Curated_BivData$hand.foci.count < 2, ]

MELT_Curated_BivData.1CO <- MELT_Curated_BivData.1CO[MELT_Curated_BivData.1CO$PER.Foci.Pos < 1.01, ]

# remove the na's
MELT_Curated_BivData.1CO <- MELT_Curated_BivData.1CO[!(is.na(MELT_Curated_BivData.1CO$hand.foci.count) | MELT_Curated_BivData.1CO$hand.foci.count==""), ]

CO.Pos.density_1CO <- ggplot(MELT_Curated_BivData.1CO, aes(x=PER.Foci.Pos, fill=strain) ) + geom_density(alpha=.2) + facet_wrap(sex~subsp, ncol=2)+ggtitle("Normalized 1CO Foci Positions")+scale_fill_manual(values=colors_of_strains)

#category specific plots, don't run for now.
Dom.female_MELT_curBivData <- MELT_Curated_BivData[ ((MELT_Curated_BivData$sex == "female") & (MELT_Curated_BivData$subsp == "Dom") ), ]
CO.Pos.density_Dom_female <- ggplot(Dom.female_MELT_curBivData, aes(x=PER.Foci.Pos, fill=strain) ) + geom_density(alpha=.2) + facet_wrap(~hand.foci.count, ncol=1)+ggtitle("Dom female \nNormalized Foci Positions")
#Musc male
Musc.male_MELT_curBivData <- MELT_Curated_BivData[ ((MELT_Curated_BivData$sex == "male") & (MELT_Curated_BivData$subsp == "Musc") ), ]

CO.Pos.density_Musc_male <- ggplot(Musc.male_MELT_curBivData, aes(x=PER.Foci.Pos, fill=strain) ) + geom_density(alpha=.2) + facet_wrap(~hand.foci.count, ncol=1)+ggtitle("Musc male \nNormalized Foci Positions")
#Dom male
Dom.male_MELT_curBivData <- MELT_Curated_BivData[ ((MELT_Curated_BivData$sex == "male") & (MELT_Curated_BivData$subsp == "Dom") ), ]

CO.Pos.density_Dom_male <- ggplot(Dom.male_MELT_curBivData, aes(x=PER.Foci.Pos, fill=strain) ) + geom_density(alpha=.2) + facet_wrap(~hand.foci.count, ncol=1)+ggtitle("Dom male \nNormalized Foci Positions")
```


```{r Q1_1COpos.t.test, echo=FALSE}

#norm.first.foci.pos  - mean nrm.F1.pos for just 1CO bivalents

Q1_1CO.pos_t.test.FULL <- t.test( ( mouse.level.BivData_table %>% filter(species == "M.musculus")  %>%  filter(sex == "male") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) )$norm.first.foci.pos,
(mouse.level.BivData_table %>% filter(species == "M.musculus")  %>%  filter(sex == "female") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) )$norm.first.foci.pos ) #<2e-16

#rerun as strain means
Q1.strain.F1.Pos <- t.test(
( strain.BivData.Table %>% filter(species == "M.musculus") %>% filter(sex == "male") %>% filter(strain != "CZECH") %>% filter(strain != "MOLF") )$mean.1CO.pos,
  
  ( strain.BivData.Table %>% filter(species == "M.musculus") %>% filter(sex == "female"))$mean.1CO.pos, paired = TRUE  )

#WSB
Q1_1CO.pos_t.test.WSB <- t.test((mouse.level.BivData_table %>% filter(sex == "male") %>% filter(strain == "WSB") )$norm.first.foci.pos,
                           (mouse.level.BivData_table %>% filter(sex == "female") %>% filter(strain == "WSB") )$norm.first.foci.pos)

#G
Q1_1CO.pos_t.test.G <- t.test((mouse.level.BivData_table %>% filter(sex == "male") %>% filter(strain == "G") )$norm.first.foci.pos,
                           (mouse.level.BivData_table %>% filter(sex == "female") %>% filter(strain == "G") )$norm.first.foci.pos)
#LEW
Q1_1CO.pos_t.test.LEW <- t.test((mouse.level.BivData_table %>% filter(sex == "male") %>% filter(strain == "LEW") )$norm.first.foci.pos,
                           (mouse.level.BivData_table %>% filter(sex == "female") %>% filter(strain == "LEW") )$norm.first.foci.pos)

#PWD
Q1_1CO.pos_t.test.PWD <- t.test((mouse.level.BivData_table %>% filter(sex == "male") %>% filter(strain == "PWD") )$norm.first.foci.pos,
                           (mouse.level.BivData_table %>% filter(sex == "female") %>% filter(strain == "PWD") )$norm.first.foci.pos)

#KAZ
Q1_1CO.pos_t.test.KAZ <- t.test((mouse.level.BivData_table %>% filter(sex == "male") %>% filter(strain == "KAZ") )$norm.first.foci.pos,
                           (mouse.level.BivData_table %>% filter(sex == "female") %>% filter(strain == "KAZ") )$norm.first.foci.pos)

#SKIVE
Q1_1CO.pos_t.test.SKIVE <- t.test((mouse.level.BivData_table %>% filter(sex == "male") %>% filter(strain == "SKIVE") )$norm.first.foci.pos,
                           (mouse.level.BivData_table %>% filter(sex == "female") %>% filter(strain == "SKIVE") )$norm.first.foci.pos)

#MSM
Q1_1CO.pos_t.test.MSM <- t.test((mouse.level.BivData_table %>% filter(sex == "male") %>% filter(strain == "MSM") )$norm.first.foci.pos,
                           (mouse.level.BivData_table %>% filter(sex == "female") %>% filter(strain == "MSM") )$norm.first.foci.pos)
```


```{r Q1.CO1pos_lmer.M1, echo=FALSE, message=FALSE}
mouse.level.BivData_table$subsp <- factor(mouse.level.BivData_table$subsp, ordered = FALSE)
mouse.level.BivData_table$sex <- factor(mouse.level.BivData_table$sex, ordered = FALSE)
mouse.level.BivData_table$strain <- factor(mouse.level.BivData_table$strain, ordered = FALSE)
mouse.level.BivData_table$species <- factor(mouse.level.BivData_table$species, ordered = FALSE)


lmer.Q1.nrm1CO_M1 <- lmer(norm.first.foci.pos ~ subsp * sex + (1|strain), 
                          data= ( mouse.level.BivData_table %>% filter(species == "M.musculus") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) %>% filter(strain !=  "TOM" ) ) )


lmer.Q1.nrm1CO_M1reduce.sex <- lmer( norm.first.foci.pos ~ subsp  +(1|strain), data=( mouse.level.BivData_table %>% filter(species == "M.musculus") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" )%>% filter(strain !=  "TOM" ) ) )

lmer.Q1.nrm1CO_M1reduce.subp <- lmer( norm.first.foci.pos ~ sex  +(1|strain), data=( mouse.level.BivData_table %>% filter(species == "M.musculus") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) %>% filter(strain !=  "TOM" )) )

lmer.Q1.nrm1CO_M1.sex <-  anova(lmer.Q1.nrm1CO_M1, lmer.Q1.nrm1CO_M1reduce.sex)$`Pr(>Chisq)`[2]
lmer.Q1.nrm1CO_M1.subp <-  anova(lmer.Q1.nrm1CO_M1, lmer.Q1.nrm1CO_M1reduce.subp)$`Pr(>Chisq)`[2]

lmer.Q1.nrm1CO_M1_interaction <- drop1(lmer.Q1.nrm1CO_M1, test="Chisq" )$`Pr(Chi)`[2]
lmer.Q1.nrm1CO_M1_strain <- exactRLRT(lmer.Q1.nrm1CO_M1)$p.value 

lmer.Q1.nrm1CO_M1_results <- data.frame(sub.sp = lmer.Q1.nrm1CO_M1.subp, 
sex.results = lmer.Q1.nrm1CO_M1.sex , 
               interaction.pval = lmer.Q1.nrm1CO_M1_interaction,  rand.pval = lmer.Q1.nrm1CO_M1_strain)

#lmer.Q1.nrm1CO_M1_results
#write.table(lmer.Q1.nrm1CO_M1_results, "~./MLH1repo/Nrm1CO_Pos_Q1_M1.csv", sep=",",row.names = TRUE)

#write_xlsx(lmer.Q1.nrm1CO_M1_results, "~./MLH1repo/Nrm1CO_Pos_Q1_M1.xlsx", col_names = TRUE)

#write.xlsx(lmer.Q1.nrm1CO_M1_results, "Nrm1CO_Pos_Q1_M1.xlsx", col.names = TRUE, row.names = TRUE)
```


```{r Q1.CO1pos_glm.M2, echo=FALSE}

#in case factors are still ordered
mouse.level.BivData_table$subsp <- factor(mouse.level.BivData_table$subsp, ordered = FALSE)
mouse.level.BivData_table$sex <- factor(mouse.level.BivData_table$sex, ordered = FALSE)
mouse.level.BivData_table$strain <- factor(mouse.level.BivData_table$strain, ordered = FALSE)

Q1.glm_F1pos_M2 <- glm(norm.first.foci.pos ~ subsp * strain * sex, data=( mouse.level.BivData_table %>% filter(species == "M.musculus") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) %>% filter(strain !=  "TOM" ) ) )

summry.Q1.glm_F1pos_M2 <- summary(Q1.glm_F1pos_M2)
#round(summry.Q1.glm_F1pos_M2$coefficients[,c(1,4)],5)

#write.table(summry.Q1.glm_F1pos_M2$coefficients, "~./MLH1repo/Nrm1CO_Pos_Q1_M2.csv", sep=",",row.names = TRUE)

#write.xlsx(summry.Q1.glm_F1pos_M2$coefficients, "Nrm1CO_Pos_Q1_M2.xlsx", col.names = TRUE)

#write_xlsx(summry.Q1.glm_F1pos_M2$coefficients, "~./MLH1repo/Nrm1CO_Pos_Q1_M2.xlsx", col_names = TRUE)


#DOM
Q1.glm_nrmF1pos_M2_Dom <- glm(norm.first.foci.pos ~ strain * sex, data=Mouse.Table_BivData_4MM[Mouse.Table_BivData_4MM$subsp == "Dom",])
#summary(Q1.glm_nrmF1pos_M2_Dom)

#MUSC
Q1.glm_nrmF1pos_M2_Musc <- glm(norm.first.foci.pos ~ strain * sex, data=Mouse.Table_BivData_4MM[Mouse.Table_BivData_4MM$subsp == "Musc",])
#summary(Q1.glm_nrmF1pos_M2_Musc)

#MOL
Q1.glm_nrmF1pos_M2_Mol <- glm(norm.first.foci.pos ~ strain * sex, data=Mouse.Table_BivData_4MM[Mouse.Table_BivData_4MM$subsp == "Mol",])
#summary(Q1.glm_nrmF1pos_M2_Mol)

```


```{r Q1.CO1pos_glm.M3, echo=FALSE, eval=TRUE}
#in case factors are ordered
mouse.level.BivData_table$subsp <- factor(mouse.level.BivData_table$subsp, ordered = FALSE)
mouse.level.BivData_table$sex <- factor(mouse.level.BivData_table$sex, ordered = FALSE)
mouse.level.BivData_table$strain <- factor(mouse.level.BivData_table$strain, ordered = FALSE)

Q1.glm_1CO.pos_M3 <- glm(norm.first.foci.pos ~ strain * sex, data=( mouse.level.BivData_table %>% filter(species == "M.musculus") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) %>% filter(strain !=  "TOM" ) ))


summry.Q1.glm_1CO.pos_M3 <- summary(Q1.glm_1CO.pos_M3)
#round(summry.Q1.glm_1CO.pos_M3$coefficients[,c(1,4)],5)
#write.table(round(summry.Q1.glm_nrmF1pos_M3$coefficients,5), "~./MLH1repo/summry.Q1.glm_nrmF1pos_M3.csv", sep=",",row.names = TRUE)

#write.table(summry.Q1.glm_1CO.pos_M3$coefficients, "~./MLH1repo/Nrm1CO_Pos_Q1_M3.csv", sep=",",row.names = TRUE)

#write.xlsx(summry.Q1.glm_1CO.pos_M3$coefficients, "Nrm1CO_Pos_Q1_M3.xlsx", col.names = TRUE)

#write_xlsx(summry.Q1.glm_1CO.pos_M3$coefficients, "~./MLH1repo/Nrm1CO_Pos_Q1_M3.xlsx", col_names = TRUE)
```


# Q1 IFD


```{r Q1.IFD_Ttests_ABS, echo=FALSE, warning=FALSE, message=FALSE}
#below are calq just from 2COs, have no fear
#mean_IFD.2CO_ABS
#mean_IFD.2CO_PER

#FULL all strains
Q1.IFD.ABS_FULL_t.test <- t.test(   (mouse.level.BivData_table %>% filter(species == "M.musculus")  %>%  filter(sex == "male") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) )$mean_IFD.2CO_ABS,
                                    
(mouse.level.BivData_table %>% filter(species == "M.musculus")  %>%  filter(sex == "female") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) )$mean_IFD.2CO_ABS    ) #0.03 (female larger)
#this comparison should be within subspecies due to strain, SC differences


#WSB
Q1.IFD.raw_t.test_WSB <- t.test( (mouse.level.BivData_table %>% filter(sex == "male") %>% filter(strain =="WSB" ))$mean_IFD.2CO_ABS,
                                (mouse.level.BivData_table %>% filter(sex == "female") %>% filter(strain =="WSB"))$mean_IFD.2CO_ABS)

#LEW
Q1.IFD.raw_t.test_LEW <- t.test( (mouse.level.BivData_table %>% filter(sex == "male") %>% filter(strain =="LEW" ))$mean_IFD.2CO_ABS,
                                ( mouse.level.BivData_table %>% filter(sex == "female") %>% filter(strain =="LEW"))$mean_IFD.2CO_ABS)

#G
Q1.IFD.raw_t.test_G <- t.test( (mouse.level.BivData_table %>% filter(sex == "male") %>% filter(strain =="G" ))$mean_IFD.2CO_ABS,
                                ( mouse.level.BivData_table %>% filter(sex == "female") %>% filter(strain =="G"))$mean_IFD.2CO_ABS)

#PWD
Q1.IFD.raw_t.test_PWD <- t.test( (mouse.level.BivData_table %>% filter(sex == "male") %>% filter(strain =="PWD" ))$mean_IFD.2CO_ABS,
                                ( mouse.level.BivData_table %>% filter(sex == "female") %>% filter(strain =="PWD"))$mean_IFD.2CO_ABS)

#KAZ - low KAZ male curation (3 mice)
Q1.IFD.raw_t.test_KAZ <- t.test( (mouse.level.BivData_table %>% filter(sex == "male") %>% filter(strain =="KAZ" ))$mean_IFD.2CO_ABS,
                                ( mouse.level.BivData_table %>% filter(sex == "female") %>% filter(strain =="KAZ"))$mean_IFD.2CO_ABS)

#SKIVE
Q1.IFD.raw_t.test_SKIVE <- t.test( (mouse.level.BivData_table %>% filter(sex == "male") %>% filter(strain =="SKIVE" ))$mean_IFD.2CO_ABS,
                                ( mouse.level.BivData_table %>% filter(sex == "female") %>% filter(strain =="SKIVE"))$mean_IFD.2CO_ABS)

#MSM - 3 male 4 female measures
#only 3 MSM males
#could be missing MSM measures, (4 females, 3 males)
Q1.IFD.raw_t.test_MSM <- t.test( (mouse.level.BivData_table %>% filter(sex == "male") %>% filter(strain =="MSM" ))$mean_IFD.2CO_ABS,
                                ( mouse.level.BivData_table %>% filter(sex == "female") %>% filter(strain =="MSM"))$mean_IFD.2CO_ABS)

#FULL all strains
Q1.IFD.raw_all <- t.test( (mouse.level.BivData_table %>% filter(sex == "male") %>% filter(strain !=  "CZECH" ) %>% filter(strain !=  "MOLF" )  %>%  filter(strain !="G") %>% filter(species == "M.musculus") )$mean_IFD.2CO_ABS,
                           
                                ( mouse.level.BivData_table %>% filter(sex == "female") %>%  filter(strain !="G")%>% filter(species == "M.musculus") )$mean_IFD.2CO_ABS)
#p-value = 0.3
```


```{r Q1.IFD_ttest_PER, echo=FALSE}

Q1.IFD.PER_FULL_t.test <- t.test(   (mouse.level.BivData_table %>% filter(species == "M.musculus")  %>%  filter(sex == "male") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) )$mean_IFD.2CO_PER,
                                    
(mouse.level.BivData_table %>% filter(species == "M.musculus")  %>%  filter(sex == "female") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) )$mean_IFD.2CO_PER    ) #p-value = 1e-10

#WSB
Q1.IFD.PER_t.test_WSB <- t.test( (mouse.level.BivData_table %>% filter(sex == "male") %>% filter(strain =="WSB" ))$mean_IFD.2CO_PER,
                                ( mouse.level.BivData_table %>% filter(sex == "female") %>% filter(strain =="WSB"))$mean_IFD.2CO_PER )#p-value = 0.03

#LEW
Q1.IFD.PER_t.test_LEW <- t.test( (mouse.level.BivData_table %>% filter(sex == "male") %>% filter(strain =="LEW"))$mean_IFD.2CO_PER,
                                ( mouse.level.BivData_table %>% filter(sex == "female") %>% filter(strain =="LEW"))$mean_IFD.2CO_PER)#p-value = 7e-05

#G
Q1.IFD.PER_t.test_G <- t.test( (mouse.level.BivData_table %>% filter(sex == "male") %>% filter(strain =="G" ))$mean_IFD.2CO_PER,
                                ( mouse.level.BivData_table %>% filter(sex == "female") %>% filter(strain =="G"))$mean_IFD.2CO_PER )#p-value = 0.03

#PWD
Q1.IFD.PER_t.test_PWD <- t.test( (mouse.level.BivData_table %>% filter(sex == "male") %>% filter(strain =="PWD" ))$mean_IFD.2CO_PER,
                                ( mouse.level.BivData_table %>% filter(sex == "female") %>% filter(strain =="PWD"))$mean_IFD.2CO_PER)#p-value = 9e-04

#KAZ
Q1.IFD.PER_t.test_KAZ <- t.test( (mouse.level.BivData_table %>% filter(sex == "male") %>% filter(strain =="KAZ" ))$mean_IFD.2CO_PER,
                                ( mouse.level.BivData_table %>% filter(sex == "female") %>% filter(strain =="KAZ"))$mean_IFD.2CO_PER)#p-value = 0.3

#MSM
Q1.IFD.PER_t.test_MSM <- t.test( (mouse.level.BivData_table %>% filter(sex == "male") %>% filter(strain =="MSM" ))$mean_IFD.2CO_PER,
                                ( mouse.level.BivData_table %>% filter(sex == "female") %>% filter(strain =="MSM"))$mean_IFD.2CO_PER)

#SKIVE
Q1.IFD.PER_t.test_SKIVE <- t.test( (mouse.level.BivData_table %>% filter(sex == "male") %>% filter(strain =="SKIVE" ))$mean_IFD.2CO_PER,
                                ( mouse.level.BivData_table %>% filter(sex == "female") %>% filter(strain =="SKIVE"))$mean_IFD.2CO_PER)

```


```{r Q1.IFD.lmer.M1, echo=FALSE, message=FALSE, warning=FALSE}

mouse.level.BivData_table$subsp <- factor(mouse.level.BivData_table$subsp, ordered = FALSE)
mouse.level.BivData_table$sex <- factor(mouse.level.BivData_table$sex, ordered = FALSE)
mouse.level.BivData_table$strain <- factor(mouse.level.BivData_table$strain, ordered = FALSE)
mouse.level.BivData_table$species <- factor(mouse.level.BivData_table$species, ordered = FALSE)

#No MOLF female curated biv data not enough time

#M1_IFD_2CO_ABS
lmer.IFD.ABS_MM.M1 <- lmer(mean_IFD.2CO_ABS ~ subsp * sex + (1|strain), data= ( mouse.level.BivData_table %>% filter(species == "M.musculus") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) %>% filter(strain !=  "TOM" ) )
                           )

lmer.IFD.ABS_MM.M1.reduce.sex <- lmer( mean_IFD.2CO_ABS ~ subsp  +(1|strain), data=( mouse.level.BivData_table %>% filter(species == "M.musculus") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) %>% filter(strain !=  "TOM" ) ) )

lmer.IFD.ABS_MM.M1.reduce.subp <- lmer( mean_IFD.2CO_ABS ~ sex  +(1|strain), data=( mouse.level.BivData_table %>% filter(species == "M.musculus") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) %>% filter(strain !=  "TOM" ) ) )

ABS.IFD_Q1.M1_sex  <- anova(lmer.IFD.ABS_MM.M1, lmer.IFD.ABS_MM.M1.reduce.sex)$`Pr(>Chisq)`[2]
ABS.IFD_Q1.M1_subsp  <- anova(lmer.IFD.ABS_MM.M1, lmer.IFD.ABS_MM.M1.reduce.subp)$`Pr(>Chisq)`[2]
ABS.IFD_Q1.M1_intr  <- drop1(lmer.IFD.ABS_MM.M1, test="Chisq" )$`Pr(Chi)`[2]
ABS.IFD_Q1.M1_strain  <- exactRLRT(lmer.IFD.ABS_MM.M1)$p.value

Q1.IFD.ABS_M1_lmer.results <- data.frame(sub.sp = ABS.IFD_Q1.M1_subsp, sex.results =  ABS.IFD_Q1.M1_sex, 
               interaction.pval = ABS.IFD_Q1.M1_intr,  rand.pval = ABS.IFD_Q1.M1_strain)

#write.table(Q1.IFD.ABS_M1_lmer.results, "~./MLH1repo/ABS.IFD_Q1_M1.csv", sep=",",row.names = TRUE)

#write_xlsx(Q1.IFD.ABS_M1_lmer.results, "~./MLH1repo/ABS.IFD_Q1_M1.xlsx", col_names = TRUE)

#write.xlsx(Q1.IFD.ABS_M1_lmer.results, "ABS.IFD_Q1_M1.xlsx", col.names = TRUE)


#oo <- ( mouse.level.BivData_table %>% filter(species == "M.musculus") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) %>% filter(strain !=  "TOM" ) )

#M1_IFD_2CO
lmer.IFD.PER_MM.M1 <- lmer(mean_IFD.2CO_PER ~ subsp * sex + (1|strain), data=
                           ( mouse.level.BivData_table %>% filter(species == "M.musculus") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) %>% filter(strain !=  "TOM" ) )
                           ) 


lmer.IFD.PER_MM.M1.reduce.sex <- lmer( mean_IFD.2CO_PER ~ subsp  +(1|strain), data=( mouse.level.BivData_table %>% filter(species == "M.musculus") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) %>% filter(strain !=  "TOM" ) )  )

lmer.IFD.PER_MM.M1.reduce.subp <- lmer( mean_IFD.2CO_PER ~ sex  +(1|strain), data= ( mouse.level.BivData_table %>% filter(species == "M.musculus") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) %>% filter(strain !=  "TOM" ) )
                                        )

sex.pval <- anova(lmer.IFD.PER_MM.M1, lmer.IFD.PER_MM.M1.reduce.sex)$`Pr(>Chisq)`[2]
subsp.pval <- anova(lmer.IFD.PER_MM.M1, lmer.IFD.PER_MM.M1.reduce.subp)$`Pr(>Chisq)`[2]
subsp.sex.pval <- drop1(lmer.IFD.PER_MM.M1, test="Chisq" )$`Pr(Chi)`[2]
strain.pval <- exactRLRT(lmer.IFD.PER_MM.M1)$p.value

Q1.IFD.PER_M1_lmer.results <- data.frame(sub.sp = subsp.pval, sex.results =  sex.pval, 
               interaction.pval = subsp.sex.pval,  rand.pval = strain.pval)

#write.table(Q1.IFD.PER_M1_lmer.results, "~./MLH1repo/PER.IFD_Q1_M1.csv", sep=",",row.names = TRUE)

#write_xlsx(Q1.IFD.PER_M1_lmer.results, "~./MLH1repo/PER.IFD_Q1_M1.xlsx", col_names = TRUE)

#write.xlsx(Q1.IFD.PER_M1_lmer.results, "PER.IFD_Q1_M1.xlsx", col.names = TRUE)

```


```{r Q1.IFD_glm.M2, echo=FALSE, warning=FALSE, message=FALSE}
#mouse.avs_4MM -- is also the bivbased mouse average table 
#Mouse.Table_BivData_4MM #this one is the HetC table (all the Curated BivData)

glm.Q1_IFD.ABS.M2  <- glm(mean_IFD.2CO_ABS ~ subsp * sex * strain, data= ( mouse.level.BivData_table %>% filter(species == "M.musculus") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) %>% filter(strain !=  "TOM" ) )
                          )

summry.glm.Q1_IFD.ABS.M2 <- summary(glm.Q1_IFD.ABS.M2)

#write.table(round(summry.glm.Q1_IFD.ABS.M2$coefficients,5), "~./MLH1repo/summry.glm.Q1_IFD.ABS.M2.csv", sep=",",row.names = TRUE)
#write.table(summry.glm.Q1_IFD.ABS.M2$coefficients, "~./MLH1repo/ABS.IFD_Q1_M2.csv", sep=",",row.names = TRUE)

#write.xlsx(summry.glm.Q1_IFD.ABS.M2$coefficients, "ABS.IFD_Q1_M2.xlsx", col.names = TRUE)

#write_xlsx(summry.glm.Q1_IFD.ABS.M2$coefficients, "~./MLH1repo/ABS.IFD_Q1_M2.xlsx", col_names = TRUE)

#PER
glm.Q1_IFD.PER.M2 <- glm(mean_IFD.2CO_PER ~ subsp * sex * strain, data= ( mouse.level.BivData_table %>% filter(species == "M.musculus") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) %>% filter(strain !=  "TOM" ) )
                         )

summry.glm.Q1_IFD.PER.M2 <- summary(glm.Q1_IFD.PER.M2)

#write.table(summry.glm.Q1_IFD.PER.M2$coefficients, "~./MLH1repo/PER.IFD_Q1_M2.csv", sep=",",row.names = TRUE)

#write.xlsx(summry.glm.Q1_IFD.PER.M2$coefficients, "PER.IFD_Q1_M2.xlsx", col.names = TRUE)

#write_xlsx(summry.glm.Q1_IFD.PER.M2$coefficients, "~./MLH1repo/PER.IFD_Q1_M2.xlsx", col_names = TRUE)
```


```{r Q1.IFD_glmM3, echo=FALSE, warning=FALSE, message=FALSE}

glm.Q1_IFD.ABS.M3  <- glm(mean_IFD.2CO_ABS ~  sex * strain, data=( mouse.level.BivData_table %>% filter(species == "M.musculus") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) %>% filter(strain !=  "TOM" ) )
                          )
summry.glm.Q1_IFD.ABS.M3 <- summary(glm.Q1_IFD.ABS.M3)

#write.table(summry.glm.Q1_IFD.ABS.M3$coefficients, "~./MLH1repo/ABS.IFD_Q1_M3.csv", sep=",",row.names = TRUE)

#write.xlsx(summry.glm.Q1_IFD.ABS.M3$coefficients, "ABS.IFD_Q1_M3.xlsx", col.names = TRUE)

#write_xlsx(summry.glm.Q1_IFD.ABS.M3$coefficients, "~./MLH1repo/ABS.IFD_Q1_M3.xlsx", col_names = TRUE)

#PER
glm.Q1_IFD.PER.M3  <- glm(mean_IFD.2CO_PER ~ sex * strain, data=( mouse.level.BivData_table %>% filter(species == "M.musculus") %>% filter(strain !=  "CAST" ) %>% filter(strain !=  "MOLF" ) %>% filter(strain !=  "HMI" ) %>% filter(strain !=  "AST" ) %>% filter(strain !=  "PERC" ) %>% filter(strain !=  "CZECH" ) %>% filter(strain !=  "TOM" ) )
                          )
summry.glm.Q1_IFD.PER.M3 <- summary(glm.Q1_IFD.PER.M3)
#round(summry.glm.Q1_IFD.PER.M3$coefficients[,c(1,4)],5)

#write.table(summry.glm.Q1_IFD.PER.M3$coefficients, "~./MLH1repo/PER.IFD_Q1_M3.csv", sep=",",row.names = TRUE)

#write.xlsx(summry.glm.Q1_IFD.PER.M3$coefficients, "PER.IFD_Q1_M3.xlsx", col.names = TRUE)

#write_xlsx(summry.glm.Q1_IFD.PER.M3$coefficients, "~./MLH1repo/PER.IFD_Q1_M3.xlsx", col_names = TRUE)

```


```{r Q1.IFD_glm.M4.M5_female, echo=FALSE}

glm.Q1_IFD.ABS.M4.female  <- glm(mean_IFD.2CO_PER ~ subsp * strain, data= (mouse.level.BivData_table %>% filter(sex == "female") ) )
summry.glm.Q1_IFD.ABS.M4.female  <- summary(glm.Q1_IFD.ABS.M4.female)
#write.table(summry.glm.Q1_IFD.PER.M3, "~./MLH1repo/PER.IFD_Q1_M3.csv", sep=",",row.names = TRUE)


glm.Q1_IFD.PER.M4.female  <- glm(mean_IFD.2CO_PER ~ subsp * strain, data= (mouse.level.BivData_table %>% filter(sex == "female") ) )
summry.glm.Q1_IFD.PER.M4.female  <- summary(glm.Q1_IFD.PER.M4.female)
#write.table(summry.glm.Q1_IFD.PER.M3, "~./MLH1repo/PER.IFD_Q1_M3.csv", sep=",",row.names = TRUE)


#M5
glm.Q1_IFD.ABS.M5.female  <- glm(mean_IFD.2CO_PER ~  strain, data= (mouse.level.BivData_table %>% filter(sex == "female") ) )
summry.glm.Q1_IFD.ABS.M5.female  <- summary(glm.Q1_IFD.ABS.M4.female)
#write.table(summry.glm.Q1_IFD.PER.M3, "~./MLH1repo/PER.IFD_Q1_M3.csv", sep=",",row.names = TRUE)


glm.Q1_IFD.PER.M5.female  <- glm(mean_IFD.2CO_PER ~  strain, data= (mouse.level.BivData_table %>% filter(sex == "female") ) )
summry.glm.Q1_IFD.PER.M5.female  <- summary(glm.Q1_IFD.PER.M5.female)
#write.table(summry.glm.Q1_IFD.PER.M3, "~./MLH1repo/PER.IFD_Q1_M3.csv", sep=",",row.names = TRUE)

```


```{r Q1.IFD_glm.M4.M5_male, echo=FALSE}

glm.Q1_IFD.ABS.M4.male  <- glm(mean_IFD.2CO_PER ~ subsp * strain, data= (mouse.level.BivData_table %>% filter(sex == "male") ) )
summry.glm.Q1_IFD.ABS.M4.male  <- summary(glm.Q1_IFD.ABS.M4.male)


glm.Q1_IFD.PER.M4.male  <- glm(mean_IFD.2CO_PER ~ subsp * strain, data= (mouse.level.BivData_table %>% filter(sex == "male") ) )
summry.glm.Q1_IFD.PER.M4.male  <- summary(glm.Q1_IFD.PER.M4.male)


#M5
glm.Q1_IFD.ABS.M5.male  <- glm(mean_IFD.2CO_PER ~  strain, data= (mouse.level.BivData_table %>% filter(sex == "male") ) )
summry.glm.Q1_IFD.ABS.M5.male  <- summary(glm.Q1_IFD.ABS.M4.male)


glm.Q1_IFD.PER.M5.male  <- glm(mean_IFD.2CO_PER ~  strain, data= (mouse.level.BivData_table %>% filter(sex == "male") ) )
summry.glm.Q1_IFD.PER.M5.male  <- summary(glm.Q1_IFD.PER.M5.male)
```


# Q2 section


# Q2 SC 


```{r Q2.totSC_male.first.comp, echo=FALSE}
#move to Q2
Q1.male.Dom.Musc.t.test <- t.test( ( mouse.total.skel %>% filter(sex == "male") %>% filter(subsp == "Dom") )$mean.skel,
(mouse.total.skel %>% filter(sex == "male") %>% filter(subsp == "Musc") )$mean.skel)

Q1.male.Dom.Mol.t.test <- t.test( ( mouse.total.skel %>% filter(sex == "male") %>% filter(subsp == "Dom") )$mean.skel,
(mouse.total.skel %>% filter(sex == "male") %>% filter(subsp == "Mol") )$mean.skel)
```


```{r Q2.SC.short.long.setup, echo=FALSE}

#table(male.long.biv$strain)
#the Long biv dataset is quite unbalance (esp MSM)
male.long.biv <- real.long.bivData %>% filter(sex== "male")

#mouse av for long biv
cell.av.long.biv.table <- ddply(male.long.biv, c("fileName"), summarise,
                             
                        n_obs = length(Obj.ID),
                         mean.SC = mean(chromosomeLength)
                         )
cell.av.long.biv.table <- add_mouse(cell.av.long.biv.table)
cell.av.long.biv.table <- add_strain(cell.av.long.biv.table)
cell.av.long.biv.table <- add_subsp(cell.av.long.biv.table)

cell.av.long.biv.table$strain <- factor(cell.av.long.biv.table$strain, ordered = FALSE)
cell.av.long.biv.table$strain <- factor(cell.av.long.biv.table$strain, ordered = FALSE)
cell.av.long.biv.table$strain <- factor(cell.av.long.biv.table$strain, ordered = FALSE)


Q2mouse.av.long.biv.table <- ddply(male.long.biv, c("mouse"), summarise,
                        n_obs = length(Obj.ID),
                         mean.SC = mean(chromosomeLength),
                        
                         #mean.first.1CO
                        norm.first.foci.pos =  mean(PER_Foci_1[which(hand.foci.count == 1)])
                         )

Q2mouse.av.long.biv.table <- add_strain(Q2mouse.av.long.biv.table)
Q2mouse.av.long.biv.table <- add_subsp(Q2mouse.av.long.biv.table)

Q2mouse.av.long.biv.table$strain <- factor(Q2mouse.av.long.biv.table$strain, ordered = FALSE)
Q2mouse.av.long.biv.table$subsp <- factor(Q2mouse.av.long.biv.table$subsp, ordered = FALSE)

#divide musc males into groups
Q2mouse.av.long.biv.table$Rec.group <- ifelse(grepl("PWD", Q2mouse.av.long.biv.table$strain), 1, 
                                  ifelse(grepl("MSM", Q2mouse.av.long.biv.table$strain), 1,
                                  ifelse(grepl("SKIVE", Q2mouse.av.long.biv.table$strain), 1,
                                           0)))


male.short.biv <- real.short.bivData %>% filter(sex== "male")

Q2mouse.av.short.biv.table <- ddply(male.short.biv, c("fileName"), summarise,
                             
                        n_obs = length(Obj.ID),
                         mean.SC = mean(chromosomeLength),
                        
                        #mean.first.1CO
                        norm.first.foci.pos =  mean(PER_Foci_1[which(hand.foci.count == 1)]
                         ) ) 

Q2mouse.av.short.biv.table <- add_mouse(Q2mouse.av.short.biv.table)
Q2mouse.av.short.biv.table <- add_strain(Q2mouse.av.short.biv.table)
Q2mouse.av.short.biv.table <- add_subsp(Q2mouse.av.short.biv.table)

Q2mouse.av.short.biv.table$strain <- factor(Q2mouse.av.short.biv.table$strain, ordered = FALSE)
Q2mouse.av.short.biv.table$subsp <- factor(Q2mouse.av.short.biv.table$subsp, ordered = FALSE)

Q2mouse.av.short.biv.table$Rec.group <- ifelse(grepl("PWD", Q2mouse.av.short.biv.table$strain), 1, 
ifelse(grepl("MSM", Q2mouse.av.short.biv.table$strain), 1,
                                  ifelse(grepl("SKIVE", Q2mouse.av.short.biv.table$strain), 1,
                                           0)))

```


```{r Q2.totSC.ttest, echo=FALSE}

#totalSC high and low rec group

Q2tot.sc_t.test_High.Low <- t.test( (mouse.total.skel %>% filter(sex == "male") %>% filter(Rec.group == "0") %>% filter(species == "M.musculus") %>% filter(subsp != "Cast") )$mean.skel,
                (mouse.total.skel %>% filter(species == "M.musculus") %>% filter(sex == "male") %>% filter(Rec.group == "1") )$mean.skel)


Q2tot.sc_t.test_High.Low_Mol <- t.test( (mouse.total.skel %>% filter(sex == "male") %>% filter(Rec.group == "0") %>% filter(subsp == "Mol") )$mean.skel,
         (mouse.total.skel %>% filter(sex == "male") %>% filter(Rec.group == "1") %>% filter(subsp == "Mol") )$mean.skel )

#musc
Q2tot.sc_t.test_High.Low_Musc <- t.test((mouse.total.skel %>% filter(sex == "male") %>% filter(Rec.group == "0") %>% filter(subsp == "Musc"))$mean.skel,
                (mouse.total.skel %>% filter(sex == "male") %>% filter(subsp == "Musc") %>% filter(Rec.group == "1") )$mean.skel)

```


```{r Q2.short.long.ttest, echo=FALSE}

#long and short 
#mouse.av.short.biv.table
#Q2mouse.av.short.biv.table

Q2short.biv_t.test_High.Low <- t.test((Q2mouse.av.short.biv.table %>% filter(Rec.group == "0") %>% filter(subsp != "Cast") )$mean.SC,
                                      (Q2mouse.av.short.biv.table %>% filter(Rec.group == "1") )$mean.SC)

#p-value = 0.9

#mouse.av.long.biv.table
Q2long.biv_t.test_High.Low <- t.test((Q2mouse.av.long.biv.table  %>% filter(Rec.group == "0") )$mean.SC,
                (Q2mouse.av.long.biv.table  %>% filter(Rec.group == "1") )$mean.SC)
#p-value = 0.2


#mUSC-short
Q2.short_t.test_High.Low.musc <- t.test((Q2mouse.av.short.biv.table  %>% filter(Rec.group == "0") %>% filter(subsp == "Musc") )$mean.SC,
                          (Q2mouse.av.short.biv.table  %>% filter(Rec.group == "1") %>% filter(subsp == "Musc"))$mean.SC)

#mol-short
#Q2.short_t.test_High.Low.mol <- t.test((Q2mouse.av.short.biv.table  %>% filter(Rec.group == "0") %>% filter(subsp == "Mol") )$mean.SC,
#                          (Q2mouse.av.short.biv.table  %>% filter(Rec.group == "1") %>% filter(subsp == "Mol"))$mean.SC)


#musc-long
Q2.long_t.test_High.Low.musc <- t.test((Q2mouse.av.long.biv.table  %>% filter(Rec.group == "0") %>% filter(subsp == "Musc") )$mean.SC,
                          (Q2mouse.av.long.biv.table  %>% filter(Rec.group == "1") %>% filter(subsp == "Musc"))$mean.SC)

#mol-long
#Q2.long_t.test_High.Low.mol <- t.test((Q2mouse.av.long.biv.table  %>% filter(Rec.group == "0") %>% filter(subsp == "Mol") )$mean.SC,
#                          (Q2mouse.av.long.biv.table  %>% filter(Rec.group == "1") %>% filter(subsp =="Mol"))$mean.SC)

#not enought observations 

```



```{r Q2.SC_HvL_allBiv, echo=FALSE}

#High-Low_All-BivData

Q2.all.BIV_t.test_HL <- t.test((Curated_BivData %>%filter(sex == "male")%>%filter(Rec.group == "0") )$chromosomeLength,
              (Curated_BivData %>%filter(sex == "male")%>%filter(Rec.group == "1"))$chromosomeLength)


#short
Q2.BIV_short_t.test_HL <- t.test((real.short.bivData %>%filter(sex == "male")%>%filter(Rec.group == "0") )$chromosomeLength,
              (real.short.bivData %>%filter(sex == "male")%>%filter(Rec.group == "1"))$chromosomeLength)

#long
Q2.BIV_long_t.test_HL <- t.test((real.long.bivData %>%filter(sex == "male")%>%filter(Rec.group == "0") )$chromosomeLength,
              (real.long.bivData %>%filter(sex == "male")%>%filter(Rec.group == "1"))$chromosomeLength)

```




```{r Q2.SC_across.subsp_tot.SC, echo=FALSE}

#Dom-Musc
Q2.totSC_t.test_DomMusc <- t.test((mouse.total.skel  %>% filter(subsp == "Dom") %>% filter(sex == "male") )$mean.skel,
                          (mouse.total.skel  %>%  filter(subsp == "Musc") %>% filter(sex == "male") )$mean.skel)
# = p-value = 8e-06

#Dom-Mol
Q2.totSC_t.test_DomMol <- t.test( (mouse.total.skel  %>% filter(subsp == "Dom") %>% filter(sex == "male") )$mean.skel,
    (mouse.total.skel  %>%  filter(subsp == "Mol") %>% filter(sex == "male") )$mean.skel )
#p-value = p-value = 2e-05

#Musc-Mol
Q2.totSC_t.test_MuscMol <- t.test( (mouse.total.skel  %>% filter(subsp == "Musc") %>% filter(sex == "male") )$mean.skel,
    (mouse.total.skel  %>%  filter(subsp == "Mol") %>% filter(sex == "male") )$mean.skel )
#p-value = 0.02

```


```{r Q2.SC_across.subsp_short.long_biv, echo=FALSE}

#DOM-MUSC-ALL
Q2.all.BIV_t.test_DomMusc <- t.test((cleanCurated_BivData %>%filter(subsp == "Dom")%>%filter(sex == "male") )$chromosomeLength,
              (cleanCurated_BivData %>% filter(subsp == "Musc")%>%filter(sex == "male"))$chromosomeLength)
#p-value = 4e-13

#DOM-MOL-ALL
Q2.all.BIV_t.test_DomMol <- t.test((cleanCurated_BivData %>%filter(subsp == "Dom")%>%filter(sex == "male") )$chromosomeLength,
              (cleanCurated_BivData %>% filter(subsp == "Mol")%>%filter(sex == "male"))$chromosomeLength)
#p-value = 6e-10

#DOM-musc-long
Q2.longBIV_t.test_DomMusc <- t.test((real.long.bivData%>%filter(subsp == "Dom")%>%filter(sex == "male") )$chromosomeLength,
              (real.long.bivData %>% filter(subsp == "Musc")%>%filter(sex == "male"))$chromosomeLength)
#p-value = 0.2

#DOM-musc-short
Q2.shortBIV_t.test_DomMusc <- t.test((real.short.bivData  %>% filter(subsp == "Dom")%>%filter(sex == "male") )$chromosomeLength,
              (real.short.bivData %>% filter(subsp == "Musc")%>%filter(sex == "male"))$chromosomeLength)
#p-value = 0.8


#DOM-mol-long
Q2.longBIV_t.test_DomMol <- t.test((real.long.bivData  %>% filter(subsp == "Dom")%>%filter(sex == "male") )$chromosomeLength,
                          (real.long.bivData %>% filter(subsp == "Mol")%>%filter(sex == "male"))$chromosomeLength)
#p-value = 0.4

#DOM-mol-short
Q2.shortBIV_t.test_DomMol <- t.test((real.short.bivData  %>% filter(subsp == "Dom")%>%filter(sex == "male") )$chromosomeLength,
                          (real.short.bivData %>% filter(subsp == "Mol")%>%filter(sex == "male"))$chromosomeLength)
#p-value = 0.06

```



re-write the blocks for M4 M5 MLH1 to total SC. to check results

```{r Female.specific.glm.M4.M5, echo=FALSE, eval=TRUE}
#Change MLH1 to mean_skel

#mean.skel
#mouse.total.skel
mouse.total.skel$strain <- factor(mouse.total.skel$strain, ordered = F)
mouse.total.skel$subsp <- factor(mouse.total.skel$subsp, ordered = F)

totSC.female.glm_M4 <- glm(mean.skel ~ subsp * strain, data= (mouse.total.skel %>% filter(subsp != "Cast") %>% filter(species == "M.musculus") %>% filter(sex == "female") ) )

sum.totSC.female.glm_M4 <- summary(totSC.female.glm_M4)

write.xlsx(as.data.frame( sum.totSC.female.glm_M4$coefficients), "totSC.female.glm_M4.xlsx", col.names = TRUE, row.names = TRUE)


totalSC.female.glm.M5 <- glm(mean.skel ~ strain, data= (mouse.total.skel %>% filter(subsp != "Cast")  %>% filter(species == "M.musculus")  %>% filter(sex == "female") ) )
sum_totalSC.female.glm.M5 <- summary(totalSC.female.glm.M5)

#write.table(sum_MLH1.female.spc.glm.M5$coefficients, "~./MLH1repo/sum_MLH1.female.spc.glm.M5.csv", sep=",",row.names = TRUE)

write.xlsx(as.data.frame( sum_totalSC.female.glm.M5$coefficients), "totalSC.female.glm.M5.xlsx", col.names = TRUE, row.names = TRUE)
```


```{r tot.SC.Male.specific.glm.M4.M5, echo=FALSE, eval=TRUE}
#mean.skel
#mouse.total.skel

mouse.total.skel$strain <- factor(mouse.total.skel$strain, ordered = F)
mouse.total.skel$subsp <- factor(mouse.total.skel$subsp, ordered = F)

#M4
totSC.male.glm.M4 <- glm(mean.skel ~ subsp * strain, data=(mouse.total.skel %>% filter(sex == "male")  %>% filter(subsp != "Cast") ) %>% filter(species == "M.musculus")   )

sum_totSC.male.glm.M4 <- summary(totSC.male.glm.M4)

#write.table(sum_MLH1.male.glm.M4$coefficients, "~./MLH1repo/MLH1_M4_male_glm.csv", sep=",",row.names = TRUE)

write.xlsx(as.data.frame(sum_totSC.male.glm.M4$coefficients), "TotSC.male.glm.M4.xlsx", col.names = TRUE, row.names = TRUE)


#M5
totSC.male.glm.M5 <- glm(mean.skel ~ strain, data= 
    (mouse.total.skel %>% filter(sex == "male")  %>% filter(subsp != "Cast") %>% filter(species == "M.musculus")) )                      

sum_totSC.male.glm.M5 <- summary(totSC.male.glm.M5)

#write.table(sum_MLH1.male.glm.M5$coefficients, "~./MLH1repo/MLH1_M5_male_glm.csv", sep=",",row.names = TRUE)

write.xlsx(as.data.frame( sum_totSC.male.glm.M5$coefficients), "TotSC.male.glm.M5.xlsx", col.names = TRUE, row.names = TRUE)

#write_xlsx(sum_MLH1.male.glm.M4.2$coefficients, "~./MLH1repo/MLH1_M5_male_glm.xlsx", col_names = TRUE)
```



```{r totalSC.M4M5, echo=FALSE}

#Q2.totl.SC <- (mouse.total.skel %>% filter(sex == "male") %>% filter(species == "M.musculus") %>% filter(subsp != "Cast") )

#M4
Q2.total.SC.male.glm.M4 <- glm(mean.skel ~ subsp * strain, data= (mouse.total.skel %>% filter(sex == "male") %>% filter(species == "M.musculus") %>% filter(subsp != "Cast") ) )

sum_Q2.total.SC.male.glm.M4 <- summary(Q2.total.SC.male.glm.M4)

#write.table(sum_MLH1.male.glm.M4$coefficients , "~./MLH1repo/MLH1_M4_male_glm.csv", sep=",",row.names = TRUE)

#M5
Q2.total.SC.male.glm.M5 <- glm( mean.skel ~ strain, data= (mouse.total.skel %>% filter(sex == "male") %>% filter(species == "M.musculus") %>% filter(subsp != "Cast") ) )

sum_Q2.total.SC.male.glm.M5 <- summary(Q2.total.SC.male.glm.M5)

#write.table(sum_MLH1.male.glm.M4.2$coefficients , "~./MLH1repo/MLH1_M5_male_glm.csv", sep=",",row.names = TRUE)


#write.table(MLH1.MMlmer_results, "~./MLH1repo/MLH1_M1_glm.csv", sep=",",row.names = TRUE)
```



```{r Q2.glm.SC.long, echo=FALSE}
Q2mouse.av.long.biv.table$strain <- factor(Q2mouse.av.long.biv.table$strain, ordered = F)
Q2mouse.av.long.biv.table$subsp <- factor(Q2mouse.av.long.biv.table$subsp, ordered = F)

#this dataset is all males
male.Long_M4 <- glm(mean.SC ~ subsp * strain, data= Q2mouse.av.long.biv.table)
sum.male.Long_M4 <- summary(male.Long_M4)

write.xlsx(as.data.frame( sum.male.Long_M4$coefficients), "male.long.M4.xlsx", col.names = TRUE, row.names = TRUE)

#Q2mouse.av.long.biv.table$um.SC <- add_umeter(Q2mouse.av.long.biv.table$mean.SC)

male.Long_M5 <- glm(mean.SC ~ strain, data= Q2mouse.av.long.biv.table)
sum.male.Long_M5 <- summary(male.Long_M5)

write.xlsx(as.data.frame( sum.male.Long_M5$coefficients), "male.Long_M5.xlsx", col.names = TRUE, row.names = TRUE)

```



```{r Q2.glm.SC.short, echo=FALSE}
#Q2mouse.av.short.biv.table
#mouse.av.short.biv.table

glmQ2_short.biv_M1 <- glm(mean.SC ~ subsp*strain, data= Q2mouse.av.short.biv.table)
sum.glmQ2_short.biv_M1 <- summary(glmQ2_short.biv_M1)

#round(summary(sum.glmQ2_short.biv_M1)$coefficients[,c(1,4)], 6)

glmQ2_short.biv_M2 <- glm(mean.SC ~ strain, data= Q2mouse.av.short.biv.table)
glmQ2_short.biv_M2 <- summary(glmQ2_short.biv_M2)

#DOM
glmQ2_short.biv_M2_DOM <- glm(mean.SC ~ strain, data= ( Q2mouse.av.short.biv.table %>% filter(subsp == "Dom") )  )
sum.glmQ2_short.biv_M2_DOM <- summary(glmQ2_short.biv_M2_DOM)

#MUSC
glmQ2_short.biv_M2_MUSC <- glm(mean.SC ~ strain, data= ( Q2mouse.av.short.biv.table %>% filter(subsp == "Musc") )  )
sum.glmQ2_short.biv_M2_MUSC <- summary(glmQ2_short.biv_M2_MUSC)

#MOL
#within subspecies

#pairwise.t.test( ( Q2mouse.av.short.biv.table %>% filter(subsp == "Dom") )$mean.SC, ( Q2mouse.av.short.biv.table %>% filter(subsp == "Dom") )$strain, p.adj = "bonf", pool.sd = FALSE)

#pairwise.t.test( ( Q2mouse.av.short.biv.table %>% filter(subsp == "Musc") )$mean.SC, ( Q2mouse.av.short.biv.table %>% filter(subsp == "Musc") )$strain, p.adj = "bonf", pool.sd = FALSE)

```



```{r Q2.SC_class.rec.group_setup, echo=FALSE, include=FALSE}
#REMOVE THIS, IT uses total bivalent data

Q2.SC_BivData_low.rec <- cleanCurated_BivData %>% filter(sex=="male") %>% filter( hand.foci.count < 5)%>% filter(Rec.group == 0 )
Q2.SC_BivData_high.rec <- cleanCurated_BivData %>% filter(sex=="male") %>% filter( hand.foci.count < 5) %>% filter(Rec.group == 1 )

#calq_mouse av
mouse.av.SC.low.rec <- ddply(Q2.SC_BivData_low.rec, c("mouse"), summarise,
                        n_obs = length(Obj.ID),
                        n_cells = length(unique(fileName) ),
                        mean.SC.total = mean(chromosomeLength),

                    mean.SC_0CO = mean(chromosomeLength[which(hand.foci.count == 0)], na.rm = TRUE),
                  n_0CO =  sum((hand.foci.count == 0), na.rm = TRUE ),
                  
                   mean.SC_1CO = mean(chromosomeLength[which(hand.foci.count == 1)], na.rm = TRUE),
                    n_1CO = sum((hand.foci.count == 1), na.rm = TRUE),
                  
                   mean.SC_2CO = mean(chromosomeLength[which(hand.foci.count == 2)], na.rm = TRUE),
                   n_2CO = sum((hand.foci.count == 2), na.rm = TRUE),
                  
                  mean.SC_3CO = mean(chromosomeLength[which(hand.foci.count == 3)], na.rm = TRUE),
                  n_3CO = sum((hand.foci.count == 3), na.rm = TRUE)
                                                
                         )

mouse.av.SC.low.rec <- add_strain(mouse.av.SC.low.rec)
mouse.av.SC.low.rec <- add_subsp(mouse.av.SC.low.rec)

mouse.av.SC.low.rec$strain <- factor(mouse.av.SC.low.rec$strain, ordered = FALSE)
mouse.av.SC.low.rec$subsp <- factor(mouse.av.SC.low.rec$subsp, ordered = FALSE)


#calq_mouse av
mouse.av.SC.high.rec <- ddply(Q2.SC_BivData_high.rec, c("mouse"), summarise,
                        n_obs = length(Obj.ID),
                         mean.SC = mean(chromosomeLength)
                         )
mouse.av.SC.high.rec <- add_mouse(mouse.av.SC.high.rec)
mouse.av.SC.high.rec <- add_strain(mouse.av.SC.high.rec)
mouse.av.SC.high.rec <- add_subsp(mouse.av.SC.high.rec)

mouse.av.SC.high.rec$strain <- factor(mouse.av.SC.high.rec$strain, ordered = FALSE)
mouse.av.SC.high.rec$add_subsp <- factor(mouse.av.SC.high.rec$subsp, ordered = FALSE)
```




# Q2 1CO postion


```{r Q2.1COpos_mouse.av.t.test_all, echo=FALSE}

#High = MSM, PWD, SKIVE
Q2.1COpos_Ttest <- t.test( (mouse.level.BivData_table %>% filter(sex == "male") %>% filter(Rec.group == 0))$norm.first.foci.pos,    
        (mouse.level.BivData_table %>% filter(sex == "male") %>% filter(Rec.group == 1))$norm.first.foci.pos )


#high = PWD and MSM
#Q2.1COpos_Ttest.HL.ex <- t.test( (mouse.avs_4MM %>% filter(sex == "male") %>% filter(Rec.group.exclu == "0"))$norm.first.foci.pos, 
#            (mouse.avs_4MM %>% filter(sex == "male") %>% filter(Rec.group.exclu == #"1"))$norm.first.foci.pos )
#p-value = 1

```


```{r Q2.1COpos_within.subsp_ttest, echo=FALSE}
#Musc
Q2.1COpos_mus.av_Musc_ttest  <-  t.test( (mouse.level.BivData_table %>%  filter(sex == "male") %>%  filter(subsp == "Musc") %>% filter(Rec.group == 0))$norm.first.foci.pos, 
                                         
            (mouse.level.BivData_table  %>%  filter(sex == "male") %>% filter(subsp == "Musc") %>% filter(Rec.group == 1))$norm.first.foci.pos )
# p-value = 0.4


#Mol
Q2.1COpos_mus.av_Mol_ttest  <-  t.test( (mouse.level.BivData_table %>%  filter(sex == "male") %>%  filter(subsp == "Mol") %>% filter(Rec.group == "0"))$norm.first.foci.pos, 
            
              (mouse.level.BivData_table  %>%  filter(sex == "male") %>% filter(subsp == "Mol") %>% filter(Rec.group == "1"))$norm.first.foci.pos   )
# p-value = 0.07
# exclusive rec group not sig
```



```{r Q2.1CO.pos_short.long.ttest, echo=FALSE}

#real.long.bivData
#single biv level
Rec.group_LONG.BivData_F1post_Ttest <- t.test(
  (real.long.bivData %>% filter(sex == "male") %>% filter(hand.foci.count == 1) %>% filter(Rec.group == "0") )$PER_Foci_1, 
(real.long.bivData %>% filter(sex == "male") %>% filter(hand.foci.count == 1) %>% filter(Rec.group == "1"))$PER_Foci_1  )
#p-value = 0.5 

Rec.group_BivData_F1post_Ttest <- t.test(
  (cleanCurated_BivData %>% filter(sex == "male") %>% filter(hand.foci.count == 1) %>% filter(Rec.group == "0") )$PER_Foci_1, 
(cleanCurated_BivData %>% filter(sex == "male") %>% filter(hand.foci.count == 1) %>% filter(Rec.group == "1"))$PER_Foci_1  )
#p-value = 0.3

```



```{r Female.1COpos.M4.M5, echo=FALSE}
#Change MLH1 to mean_skel

#Pos  PER_Foci_1
#cleanCurated_BivData

cleanCurated_BivData$strain <- factor(cleanCurated_BivData$strain, ordered = F)
cleanCurated_BivData$subsp <- factor(cleanCurated_BivData$subsp, ordered = F)

chrm.1CO.pos.female.glm_M4 <- glm(PER_Foci_1 ~ subsp * strain, data= (cleanCurated_BivData %>% filter(subsp != "Cast") %>% filter(species == "M.musculus") %>% filter(sex == "female") ) )

sum.chrm.1CO.pos.female.glm_M4 <- summary(chrm.1CO.pos.female.glm_M4)

#write.xlsx(as.data.frame( sum.chrm.1CO.pos.female.glm_M4$coefficients), "chrm.1CO.pos.female.glm_M4.xlsx", col.names = TRUE, row.names = TRUE)


chrm.1CO.pos.female.glm_M5 <- glm(PER_Foci_1 ~ strain, data= (cleanCurated_BivData %>% filter(subsp != "Cast")  %>% filter(species == "M.musculus")  %>% filter(sex == "female") ) )
sum_chrm.1CO.pos.female.glm_M5 <- summary(chrm.1CO.pos.female.glm_M5)

#write.table(sum_MLH1.female.spc.glm.M5$coefficients, "~./MLH1repo/sum_MLH1.female.spc.glm.M5.csv", sep=",",row.names = TRUE)

#write.xlsx(as.data.frame( sum_chrm.1CO.pos.female.glm_M5$coefficients), "chrm.1CO.pos.female.glm_M5.xlsx", col.names = TRUE, row.names = TRUE)
```


```{r Male.Q2.1COpos_male_M4.M5, echo=FALSE}

#norm.first.foci.pos AND mean_1CO.pos.PER  are the same

male_1COpos.glm_M4 <- glm(norm.first.foci.pos ~ subsp * strain, data = (mouse.level.BivData_table  %>% filter(sex == "male") %>% filter(species == "M.musculus")  ) )

sum.male_1COpos.glm_M4  <- summary(male_1COpos.glm_M4)
#summary(Q2.glm_mus.av_1COpos_M1)$coefficients[,4]

write.xlsx(as.data.frame( sum.male_1COpos.glm_M4$coefficients), "male_1COpos.glm_M4.xlsx", col.names = TRUE, row.names = TRUE)


#M5 (just strain)
male_1COpos.glm_M5 <- glm(norm.first.foci.pos ~ strain, data= mouse.level.BivData_table %>% filter(sex == "male") %>% filter(species == "M.musculus") )

sum.male_1COpos.glm_M5 <- summary(male_1COpos.glm_M5)

write.xlsx(as.data.frame( sum.male_1COpos.glm_M5$coefficients), "male_1COpos.glm_M5.xlsx", col.names = TRUE, row.names = TRUE)

```



```{r Q2.1CO.pos_glm.chrm.Length, echo=FALSE}
#remove this cell, 

cleanCurated_BivData <- cleanCurated_BivData %>% filter(Obj.ID != "13sep18_28jun18_MOLF_m1_sp1_18.1_rev_14")

#making new models 

cleanCurated_BivData$subsp <- factor(cleanCurated_BivData$subsp , ordered = F)
cleanCurated_BivData$strain <- factor(cleanCurated_BivData$strain , ordered = F)

chrm.1CO.pos.chrmLength <- glm(PER_Foci_1 ~ chromosomeLength * subsp * strain, data= ( cleanCurated_BivData %>% filter(sex == "male")  %>%  filter(hand.foci.count == "1") ) )

sum.chrm.1CO.pos.chrmLength <- summary(chrm.1CO.pos.chrmLength)$coefficients
#summary(Q2.glm_mus.av_1COpos_M1)$coefficients[,4]


chrm.1CO.pos.chrmLength_strain <- glm(PER_Foci_1 ~ chromosomeLength *  strain, data= Curated_BivData %>% filter(sex == "male")  %>%  filter(hand.foci.count == "1") )

#summary(chrm.1CO.pos.chrmLength_strain)

```




# Q2 IFD



```{r Q2.IFD.long.short.setup, echo=FALSE}
#long BivData
male.long.biv.2CO_IFD <- real.long.bivData %>% filter(sex== "male") %>% filter(species =="M.musculus") %>% filter(hand.foci.count == 2)

male.long.biv.2CO_IFD$Rec.group <- ifelse(grepl("PWD", male.long.biv.2CO_IFD$strain), 1, 
                                    ifelse(grepl("MSM", male.long.biv.2CO_IFD$strain), 1, 
                                           ifelse(grepl("SKIVE", male.long.biv.2CO_IFD$strain), 1, 0)))

#show
Long.biv.IFDs_PER_by.group <- ggplot(male.long.biv.2CO_IFD, aes(y = IFD1_PER, x= mouse, color=strain))+geom_boxplot(alpha=.2)+
  geom_jitter(alpha=.2)+
  ggtitle("Normalized Interfocal Distances, Long BivData\nLow Rec group =0, High Rec group =1")+
  scale_color_manual(values=colors_of_strains)+ facet_wrap(subsp~Rec.group, scales = "free")+theme(legend.position="none")+ylim(c(0,1.1))

#long biv's - short IFD rates

LongBiv_IFD_mus.rate <- ddply(male.long.biv.2CO_IFD %>% filter(sex== "male") %>% filter(species =="M.musculus") %>% filter(hand.foci.count == 2), 
                         c("mouse"), summarise,
                        
                   N.obs  = length(Obj.ID),

                  mean.ABS.IFD = mean(IFD1_ABS, na.rm = TRUE),  
                  mean.per.IFD = mean(IFD1_PER, na.rm=TRUE),
                  var.IFD = var(IFD1_PER, na.rm=TRUE),
                        
                  #mean_IFD_short.removed
                  mean.perIFD_short.rm = mean(  IFD1_PER[which(IFD1_PER >= .3)], na.rm=TRUE),
                mean.absIFD_short.rm = mean(  IFD1_ABS[which(IFD1_PER >= .3)] ),
                
                inverse.close.foci = length(which(IFD1_PER >= .31)),  
                n.close.foci = length(which(IFD1_PER <= .3)),
                      
                off.by = (N.obs - sum(c(inverse.close.foci,n.close.foci)) ),
                      
                rate.close.foci = n.close.foci / N.obs
                
                                              )

#run t.tests on long biv
LongBiv_IFD_mus.rate <- add_strain(LongBiv_IFD_mus.rate)
LongBiv_IFD_mus.rate <- add_category(LongBiv_IFD_mus.rate)
LongBiv_IFD_mus.rate <- add_subsp(LongBiv_IFD_mus.rate)

#add rec.group
LongBiv_IFD_mus.rate$Rec.group <- ifelse(grepl("PWD", LongBiv_IFD_mus.rate$strain), 1, 
                                ifelse(grepl("MSM", LongBiv_IFD_mus.rate$strain), 1,
                                 ifelse(grepl("SKIVE", LongBiv_IFD_mus.rate$strain), 1, 0)))

```


```{r Q2.IFD.long.biv_t.test, echo=FALSE}
#short removed PER
Short.removed_BivData.LongBiv_IFD.PER_Ttest <- t.test(LongBiv_IFD_mus.rate$mean.perIFD_short.rm[LongBiv_IFD_mus.rate$Rec.group == 1], 
                                 LongBiv_IFD_mus.rate$mean.perIFD_short.rm[LongBiv_IFD_mus.rate$Rec.group == 0])
 
#Short.removed_BivData.LongBiv_IFD.PER_Ttest$p.value
#0.0083

#ABS short removed
Short.removed_BivData.LongBiv_IFD.ABS_Ttest <- t.test(LongBiv_IFD_mus.rate$mean.absIFD_short.rm[LongBiv_IFD_mus.rate$Rec.group == 1], 
                                 LongBiv_IFD_mus.rate$mean.absIFD_short.rm[LongBiv_IFD_mus.rate$Rec.group == 0])

#Short.removed_BivData.LongBiv_IFD.ABS_Ttest$p.value
#0.047
```


```{r Q2.t.test_IFD_mouse.av, echo=FALSE, eval=TRUE}
#t.test for IFD
#mouse.av - the mouse average IFD is from just 2CO

#high, low
t.test_mouse.av.IFD_ABS <- t.test(  (mouse.level.BivData_table %>% filter(Rec.group == "1") %>% filter(sex == "male") %>% filter(species == "M.musculus")  )$mean_IFD.2CO_ABS, 
   (mouse.level.BivData_table %>% filter(Rec.group == "0") %>% filter(sex == "male")%>% filter(species == "M.musculus") )$mean_IFD.2CO_ABS   )
  

t.test_mouse.av.IFD_PER <- t.test(  (mouse.level.BivData_table %>% filter(Rec.group == "1") %>% filter(sex == "male") )$mean_IFD.2CO_PER,
   (mouse.level.BivData_table %>% filter(Rec.group == "0") %>% filter(sex == "male") %>% filter(species == "M.musculus") )$mean_IFD.2CO_PER   )


#t.test_mouse.av.IFD_PER_DOM <- t.test(  (mouse.avs_4MM %>% filter(Rec.group == "1") %>% filter(sex == #"male") %>% filter(subsp == "Dom") )$mean_IFD.2CO_PER,
#   (mouse.avs_4MM %>% filter(Rec.group == "0") %>% filter(sex == "male")  %>% filter(subsp == #"Dom"))$mean_IFD.2CO_PER   )

t.test_mouse.av.IFD_PER_MUSC <- t.test(  (mouse.level.BivData_table %>% filter(Rec.group == "1") %>% filter(sex == "male") %>% filter(subsp == "Musc") %>% filter(species == "M.musculus") )$mean_IFD.2CO_PER,
   (mouse.level.BivData_table %>% filter(Rec.group == "0") %>% filter(sex == "male")  %>% filter(subsp == "Musc") %>% filter(species == "M.musculus") )$mean_IFD.2CO_PER   )

#ABS
t.test_mouse.av.IFD_ABS_MUSC <- t.test(  (mouse.level.BivData_table %>% filter(Rec.group == "1") %>% filter(sex == "male") %>% filter(subsp == "Musc") %>% filter(species == "M.musculus"))$mean_IFD.2CO_ABS,
   (mouse.level.BivData_table %>% filter(Rec.group == "0") %>% filter(sex == "male")  %>% filter(subsp == "Musc")%>% filter(species == "M.musculus"))$mean_IFD.2CO_ABS   )

#niether PER or ABS is sig, 1 mouse, #1feb18_MSM_m1 has only 1 observation 

t.test_mouse.av.IFD_PER_MOL <- t.test(  (mouse.level.BivData_table %>% filter(Rec.group == "1") %>% filter(sex == "male") %>% filter(subsp == "Mol") %>% filter(mouse != "1feb18_MSM_m1")   )$mean_IFD.2CO_PER,
   (mouse.level.BivData_table %>% filter(Rec.group == "0") %>% filter(sex == "male") %>% filter(subsp == "Mol") %>% filter(species == "M.musculus") )$mean_IFD.2CO_PER   )

t.test_mouse.av.IFD_ABS_MOL <- t.test(  (mouse.level.BivData_table %>% filter(Rec.group == "1") %>% filter(sex == "male") %>% filter(subsp == "Mol") %>% filter(mouse != "1feb18_MSM_m1") )$mean_IFD.2CO_ABS,
   (mouse.level.BivData_table %>% filter(Rec.group == "0") %>% filter(sex == "male") %>% filter(subsp == "Mol") )$mean_IFD.2CO_ABS  )

```



```{r Q2.show.IFD.Mol, echo=FALSE}

#mouse.level.BivData_table
#cleanCurated_BivData

Musc.IFD.Biv <- ggplot(data = (cleanCurated_BivData %>% filter(subsp == "Musc") %>% filter(sex == "male") %>% filter(hand.foci.count == 2)  ), aes(x = strain, y = IFD1_PER) ) + geom_jitter()

Mol.IFD <- ggplot(data = (cleanCurated_BivData %>% filter(subsp == "Mol") %>% filter(sex == "male") %>% filter(hand.foci.count == 2)  ), aes(x = strain, y = IFD1_PER) ) + geom_jitter() +facet_wrap(~mouse)

t.test_biv.av.IFD_PER_MOL <- t.test(  (cleanCurated_BivData %>% filter(Rec.group == "1") %>% filter(sex == "male") %>% filter(subsp == "Mol") %>% filter(species == "M.musculus") )$IFD1_PER,
   (cleanCurated_BivData %>% filter(Rec.group == "0") %>% filter(sex == "male") %>% filter(subsp == "Mol") %>% filter(species == "M.musculus") )$IFD1_PER   )
#p value for the bivalent level IFD1 norm positions are significant


#mouse level
t.test_mouse.av.IFD_PER_MOL <- t.test(  (mouse.level.BivData_table %>% filter(Rec.group == "1") %>% filter(sex == "male") %>% filter(subsp == "Mol") %>% filter(species == "M.musculus") )$mean_IFD.2CO_PER,
   (mouse.level.BivData_table %>% filter(Rec.group == "0") %>% filter(sex == "male") %>% filter(subsp == "Mol") %>% filter(species == "M.musculus") )$mean_IFD.2CO_PER   )

#1feb18_MSM_m1

Mol.mus.IFD <- ggplot(data = (mouse.level.BivData_table %>% filter(subsp == "Mol") %>% filter(sex == "male")   ), aes(x = strain, y = mean_IFD_PER, color = mouse) ) + geom_jitter()
#there is mouse MSM with v low, 1feb18_MSM_m1 -- it only has 1 measure
```


```{r Female.IFD.M4.M5, echo=FALSE}
#mean_IFD.2CO_ABS
#mouse.level.BivData_table

mouse.level.BivData_table$strain <- factor(mouse.level.BivData_table$strain, ordered = F)
mouse.level.BivData_table$subsp <- factor(mouse.level.BivData_table$subsp, ordered = F)

#RAW IFD
IFD.raw.female.glm_M4 <- glm(mean_IFD.2CO_ABS ~ subsp * strain, data= (mouse.level.BivData_table %>% filter(subsp != "Cast") %>% filter(species == "M.musculus") %>% filter(sex == "female") ) )
sum.IFD.raw.female.glm_M4 <- summary(IFD.raw.female.glm_M4)
write.xlsx(as.data.frame( sum.IFD.raw.female.glm_M4$coefficients), "IFD.raw.female.glm_M4.xlsx", col.names = TRUE, row.names = TRUE)

IFD.raw.female.glm_M5 <- glm(mean_IFD.2CO_ABS ~ strain, data= (mouse.level.BivData_table %>% filter(subsp != "Cast")  %>% filter(species == "M.musculus")  %>% filter(sex == "female") ) )
sum_IFD.raw.female.glm_M5 <- summary(IFD.raw.female.glm_M5)
write.xlsx(as.data.frame( sum_IFD.raw.female.glm_M5$coefficients), "IFD.raw.female.glm_M5.xlsx", col.names = TRUE, row.names = TRUE)

#PER IFD
IFD.PER.female.glm_M4 <- glm(mean_IFD.2CO_PER ~ subsp * strain, data= (mouse.level.BivData_table %>% filter(subsp != "Cast") %>% filter(species == "M.musculus") %>% filter(sex == "female") ) )

sum.IFD.PER.female.glm_M4 <- summary(IFD.PER.female.glm_M4)
write.xlsx(as.data.frame( sum.IFD.PER.female.glm_M4$coefficients), "IFD.PER.female.glm_M4.xlsx", col.names = TRUE, row.names = TRUE)


IFD.PER.female.glm_M5 <- glm(mean_IFD.2CO_PER ~ strain, data= (mouse.level.BivData_table %>% filter(subsp != "Cast")  %>% filter(species == "M.musculus")  %>% filter(sex == "female") ) )
sum_IFD.PER.female.glm_M5 <- summary(IFD.PER.female.glm_M5)

write.xlsx(as.data.frame( sum_IFD.PER.female.glm_M5$coefficients), "IFD.PER.female.glm_M5.xlsx", col.names = TRUE, row.names = TRUE)

```



```{r Male.Q2.IFD_male_M4.M5, echo=FALSE}

#RAW IFD
IFD.raw.male.glm_M4 <- glm(mean_IFD.2CO_ABS ~ subsp * strain, data= (mouse.level.BivData_table %>% filter(subsp != "Cast") %>% filter(species == "M.musculus") %>% filter(sex == "male") ) )
sum.IFD.raw.male.glm_M4 <- summary(IFD.raw.male.glm_M4)
write.xlsx(as.data.frame( sum.IFD.raw.male.glm_M4$coefficients), "IFD.raw.male.glm_M4.xlsx", col.names = TRUE, row.names = TRUE)

IFD.raw.male.glm_M5 <- glm(mean_IFD.2CO_ABS ~ strain, data= (mouse.level.BivData_table %>% filter(subsp != "Cast")  %>% filter(species == "M.musculus")  %>% filter(sex == "male") ) )
sum_IFD.raw.male.glm_M5 <- summary(IFD.raw.male.glm_M5)
write.xlsx(as.data.frame( sum_IFD.raw.male.glm_M5$coefficients), "IFD.raw.male.glm_M5.xlsx", col.names = TRUE, row.names = TRUE)

#PER IFD
IFD.PER.male.glm_M4 <- glm(mean_IFD.2CO_PER ~ subsp * strain, data= (mouse.level.BivData_table %>% filter(subsp != "Cast") %>% filter(species == "M.musculus") %>% filter(sex == "male") ) )
sum.IFD.PER.male.glm_M4 <- summary(IFD.PER.male.glm_M4)
write.xlsx(as.data.frame( sum.IFD.PER.male.glm_M4$coefficients), "IFD.PER.male.glm_M4.xlsx", col.names = TRUE, row.names = TRUE)

IFD.PER.male.glm_M5 <- glm(mean_IFD.2CO_PER ~ strain, data= (mouse.level.BivData_table %>% filter(subsp != "Cast")  %>% filter(species == "M.musculus")  %>% filter(sex == "male") ) )
sum_IFD.PER.male.glm_M5 <- summary(IFD.PER.male.glm_M5)

write.xlsx(as.data.frame( sum_IFD.PER.male.glm_M5$coefficients), "IFD.PER.male.glm_M5.xlsx", col.names = TRUE, row.names = TRUE)

```



```{r Q2.IFD.glm.test, echo=FALSE}

#M4.ABS
Q2.M4glm_IFD.raw <- glm(mean_IFD.2CO_ABS ~ subsp * strain, data= mouse.level.BivData_table %>% filter(sex == "male")  %>% filter(species == "M.musculus")  )
sum.Q2.M4glm_IFD.raw <- summary(Q2.M4glm_IFD.raw) 

#M4.PER
Q2.M4glm_IFD.PER <- glm(mean_IFD.2CO_PER ~ subsp * strain, data= mouse.level.BivData_table %>% filter(sex == "male") %>% filter(species == "M.musculus")  )

sum.Q2.M4glm_IFD.PER <- summary(Q2.M4glm_IFD.PER)
#summary(Q2.M1glm_IFD.PER) 

#M4.2.raw
Q2.M4.2glm_IFD.raw <- glm(mean_IFD.2CO_ABS ~ strain, data= mouse.level.BivData_table %>% filter(sex == "male") %>% filter(species == "M.musculus") )
Sum.Q2.M4.2glm_IFD.raw <- summary(Q2.M4.2glm_IFD.raw)

Q2.M4.2glm_IFD.PER <- glm(mean_IFD.2CO_PER ~ strain, data= mouse.level.BivData_table %>% filter(sex == "male") %>% filter(species == "M.musculus") )
sum.Q2.M4.2glm_IFD.PER <- summary(Q2.M4.2glm_IFD.PER)
#  MSM strain effect for 2CO PER not significant

#within subspecies
#Dom
#Q2.glm.M4.2_IFD_Dom <- glm(mean_IFD.2CO_ABS ~ strain, data= Male.poly.Mouse.Table_BivData_4MM[Male.poly.Mouse.Table_BivData_4MM$subsp == "Dom",])
#summary(Q2.glm.M4.2_IFD_Dom)

#Musc
#Q2.glm.M4.2_IFD_Musc <- glm(mean_IFD.2CO_ABS ~ strain, data= Male.poly.Mouse.Table_BivData_4MM[Male.poly.Mouse.Table_BivData_4MM$subsp == "Musc",])
#summary(Q2.glm.M4.2_IFD_Musc)

#Mol
#Q2.glm.M4.2_IFD_Mol <- glm(mean_IFD.2CO_ABS ~ strain, data= Male.poly.Mouse.Table_BivData_4MM[Male.poly.Mouse.Table_BivData_4MM$subsp == "Mol",])
#summary(Q2.glm.M4.2_IFD_Mol)

#Dom
#Q2.glm.M4.2_IFD.PER_Dom <- glm(mean_IFD.2CO_PER ~ strain, data= Male.poly.Mouse.Table_BivData_4MM[Male.poly.Mouse.Table_BivData_4MM$subsp == "Dom",])
#summary(Q2.glm.M4.2_IFD.PER_Dom) 

#Musc
#Q2.glm.M4.2_IFD.PER_Musc <- glm(mean_IFD.2CO_PER ~ strain, data= Male.poly.Mouse.Table_BivData_4MM[Male.poly.Mouse.Table_BivData_4MM$subsp == "Musc",])
#summary(Q2.glm.M4.2_IFD.PER_Musc) 

#Mol
#Q2.glm.M4.2_IFD.PER_Mol <- glm(mean_IFD.2CO_PER ~ strain, data= Male.poly.Mouse.Table_BivData_4MM[Male.poly.Mouse.Table_BivData_4MM$subsp == "Mol",])
#summary(Q2.glm.M4.2_IFD.PER_Mol)
```

# SAVE the data

```{r Save.File, echo=FALSE}
#save Rdata for using in Rmd for manuscript.
save.image("~./MeioticRecombSexualDimorphism/data/Results_setup_5.30.20.RData")

```
